/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainUsesRouteImport } from './routes/_main/uses'
import { Route as MainMusicRouteImport } from './routes/_main/music'
import { Route as MainGalleryRouteImport } from './routes/_main/gallery'
import { Route as MainDesignSystemRouteImport } from './routes/_main/design-system'
import { Route as MainWatchingIndexRouteImport } from './routes/_main/watching/index'
import { Route as MainProjectsIndexRouteImport } from './routes/_main/projects/index'
import { Route as MainLabsIndexRouteImport } from './routes/_main/labs/index'
import { Route as MainGamesIndexRouteImport } from './routes/_main/games/index'
import { Route as MainBlogIndexRouteImport } from './routes/_main/blog/index'
import { Route as MainWatchingRkeyRouteImport } from './routes/_main/watching/$rkey'
import { Route as MainProjectsNameRouteImport } from './routes/_main/projects/$name'
import { Route as MainLabsVerseRevealRouteImport } from './routes/_main/labs/verse-reveal'
import { Route as MainLabsTidRouteImport } from './routes/_main/labs/tid'
import { Route as MainLabsScreenshotMakerRouteImport } from './routes/_main/labs/screenshot-maker'
import { Route as MainLabsPdfUploaderRouteImport } from './routes/_main/labs/pdf-uploader'
import { Route as MainLabsPaletteRouteImport } from './routes/_main/labs/palette'
import { Route as MainLabsListCleanerRouteImport } from './routes/_main/labs/list-cleaner'
import { Route as MainLabsJetstreamRouteImport } from './routes/_main/labs/jetstream'
import { Route as MainLabsInfiniteCanvasRouteImport } from './routes/_main/labs/infinite-canvas'
import { Route as MainGamesRkeyRouteImport } from './routes/_main/games/$rkey'
import { Route as MainBlogRkeyRouteImport } from './routes/_main/blog/$rkey'
import { Route as MainLabsPlcLogIndexRouteImport } from './routes/_main/labs/plc-log/index'
import { Route as MainLabsLexiconIndexRouteImport } from './routes/_main/labs/lexicon/index'
import { Route as MainLabsFeedIndexRouteImport } from './routes/_main/labs/feed/index'
import { Route as MainLabsCssBattlesIndexRouteImport } from './routes/_main/labs/css-battles/index'
import { Route as MainLabsCarExplorerIndexRouteImport } from './routes/_main/labs/car-explorer/index'
import { Route as MainLabsAtUriIndexRouteImport } from './routes/_main/labs/at-uri/index'
import { Route as MainLabsPlcLogSplatRouteImport } from './routes/_main/labs/plc-log/$'
import { Route as MainLabsLexiconNsidRouteImport } from './routes/_main/labs/lexicon/$nsid'
import { Route as MainLabsFeedSplatRouteImport } from './routes/_main/labs/feed/$'
import { Route as MainLabsCssBattlesDateRouteImport } from './routes/_main/labs/css-battles/$date'
import { Route as MainLabsCarExplorerSplatRouteImport } from './routes/_main/labs/car-explorer/$'
import { Route as MainLabsAtUriSplatRouteImport } from './routes/_main/labs/at-uri/$'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainUsesRoute = MainUsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => MainRoute,
} as any)
const MainMusicRoute = MainMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => MainRoute,
} as any)
const MainGalleryRoute = MainGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => MainRoute,
} as any)
const MainDesignSystemRoute = MainDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => MainRoute,
} as any)
const MainWatchingIndexRoute = MainWatchingIndexRouteImport.update({
  id: '/watching/',
  path: '/watching/',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsIndexRoute = MainProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsIndexRoute = MainLabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => MainRoute,
} as any)
const MainGamesIndexRoute = MainGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogIndexRoute = MainBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => MainRoute,
} as any)
const MainWatchingRkeyRoute = MainWatchingRkeyRouteImport.update({
  id: '/watching/$rkey',
  path: '/watching/$rkey',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsNameRoute = MainProjectsNameRouteImport.update({
  id: '/projects/$name',
  path: '/projects/$name',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsVerseRevealRoute = MainLabsVerseRevealRouteImport.update({
  id: '/labs/verse-reveal',
  path: '/labs/verse-reveal',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsTidRoute = MainLabsTidRouteImport.update({
  id: '/labs/tid',
  path: '/labs/tid',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsScreenshotMakerRoute = MainLabsScreenshotMakerRouteImport.update({
  id: '/labs/screenshot-maker',
  path: '/labs/screenshot-maker',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsPdfUploaderRoute = MainLabsPdfUploaderRouteImport.update({
  id: '/labs/pdf-uploader',
  path: '/labs/pdf-uploader',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsPaletteRoute = MainLabsPaletteRouteImport.update({
  id: '/labs/palette',
  path: '/labs/palette',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsListCleanerRoute = MainLabsListCleanerRouteImport.update({
  id: '/labs/list-cleaner',
  path: '/labs/list-cleaner',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsJetstreamRoute = MainLabsJetstreamRouteImport.update({
  id: '/labs/jetstream',
  path: '/labs/jetstream',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsInfiniteCanvasRoute = MainLabsInfiniteCanvasRouteImport.update({
  id: '/labs/infinite-canvas',
  path: '/labs/infinite-canvas',
  getParentRoute: () => MainRoute,
} as any)
const MainGamesRkeyRoute = MainGamesRkeyRouteImport.update({
  id: '/games/$rkey',
  path: '/games/$rkey',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogRkeyRoute = MainBlogRkeyRouteImport.update({
  id: '/blog/$rkey',
  path: '/blog/$rkey',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsPlcLogIndexRoute = MainLabsPlcLogIndexRouteImport.update({
  id: '/labs/plc-log/',
  path: '/labs/plc-log/',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsLexiconIndexRoute = MainLabsLexiconIndexRouteImport.update({
  id: '/labs/lexicon/',
  path: '/labs/lexicon/',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsFeedIndexRoute = MainLabsFeedIndexRouteImport.update({
  id: '/labs/feed/',
  path: '/labs/feed/',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCssBattlesIndexRoute = MainLabsCssBattlesIndexRouteImport.update({
  id: '/labs/css-battles/',
  path: '/labs/css-battles/',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCarExplorerIndexRoute =
  MainLabsCarExplorerIndexRouteImport.update({
    id: '/labs/car-explorer/',
    path: '/labs/car-explorer/',
    getParentRoute: () => MainRoute,
  } as any)
const MainLabsAtUriIndexRoute = MainLabsAtUriIndexRouteImport.update({
  id: '/labs/at-uri/',
  path: '/labs/at-uri/',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsPlcLogSplatRoute = MainLabsPlcLogSplatRouteImport.update({
  id: '/labs/plc-log/$',
  path: '/labs/plc-log/$',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsLexiconNsidRoute = MainLabsLexiconNsidRouteImport.update({
  id: '/labs/lexicon/$nsid',
  path: '/labs/lexicon/$nsid',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsFeedSplatRoute = MainLabsFeedSplatRouteImport.update({
  id: '/labs/feed/$',
  path: '/labs/feed/$',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCssBattlesDateRoute = MainLabsCssBattlesDateRouteImport.update({
  id: '/labs/css-battles/$date',
  path: '/labs/css-battles/$date',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCarExplorerSplatRoute =
  MainLabsCarExplorerSplatRouteImport.update({
    id: '/labs/car-explorer/$',
    path: '/labs/car-explorer/$',
    getParentRoute: () => MainRoute,
  } as any)
const MainLabsAtUriSplatRoute = MainLabsAtUriSplatRouteImport.update({
  id: '/labs/at-uri/$',
  path: '/labs/at-uri/$',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/design-system': typeof MainDesignSystemRoute
  '/gallery': typeof MainGalleryRoute
  '/music': typeof MainMusicRoute
  '/uses': typeof MainUsesRoute
  '/blog/$rkey': typeof MainBlogRkeyRoute
  '/games/$rkey': typeof MainGamesRkeyRoute
  '/labs/infinite-canvas': typeof MainLabsInfiniteCanvasRoute
  '/labs/jetstream': typeof MainLabsJetstreamRoute
  '/labs/list-cleaner': typeof MainLabsListCleanerRoute
  '/labs/palette': typeof MainLabsPaletteRoute
  '/labs/pdf-uploader': typeof MainLabsPdfUploaderRoute
  '/labs/screenshot-maker': typeof MainLabsScreenshotMakerRoute
  '/labs/tid': typeof MainLabsTidRoute
  '/labs/verse-reveal': typeof MainLabsVerseRevealRoute
  '/projects/$name': typeof MainProjectsNameRoute
  '/watching/$rkey': typeof MainWatchingRkeyRoute
  '/blog/': typeof MainBlogIndexRoute
  '/games/': typeof MainGamesIndexRoute
  '/labs/': typeof MainLabsIndexRoute
  '/projects/': typeof MainProjectsIndexRoute
  '/watching/': typeof MainWatchingIndexRoute
  '/labs/at-uri/$': typeof MainLabsAtUriSplatRoute
  '/labs/car-explorer/$': typeof MainLabsCarExplorerSplatRoute
  '/labs/css-battles/$date': typeof MainLabsCssBattlesDateRoute
  '/labs/feed/$': typeof MainLabsFeedSplatRoute
  '/labs/lexicon/$nsid': typeof MainLabsLexiconNsidRoute
  '/labs/plc-log/$': typeof MainLabsPlcLogSplatRoute
  '/labs/at-uri/': typeof MainLabsAtUriIndexRoute
  '/labs/car-explorer/': typeof MainLabsCarExplorerIndexRoute
  '/labs/css-battles/': typeof MainLabsCssBattlesIndexRoute
  '/labs/feed/': typeof MainLabsFeedIndexRoute
  '/labs/lexicon/': typeof MainLabsLexiconIndexRoute
  '/labs/plc-log/': typeof MainLabsPlcLogIndexRoute
}
export interface FileRoutesByTo {
  '/design-system': typeof MainDesignSystemRoute
  '/gallery': typeof MainGalleryRoute
  '/music': typeof MainMusicRoute
  '/uses': typeof MainUsesRoute
  '/': typeof MainIndexRoute
  '/blog/$rkey': typeof MainBlogRkeyRoute
  '/games/$rkey': typeof MainGamesRkeyRoute
  '/labs/infinite-canvas': typeof MainLabsInfiniteCanvasRoute
  '/labs/jetstream': typeof MainLabsJetstreamRoute
  '/labs/list-cleaner': typeof MainLabsListCleanerRoute
  '/labs/palette': typeof MainLabsPaletteRoute
  '/labs/pdf-uploader': typeof MainLabsPdfUploaderRoute
  '/labs/screenshot-maker': typeof MainLabsScreenshotMakerRoute
  '/labs/tid': typeof MainLabsTidRoute
  '/labs/verse-reveal': typeof MainLabsVerseRevealRoute
  '/projects/$name': typeof MainProjectsNameRoute
  '/watching/$rkey': typeof MainWatchingRkeyRoute
  '/blog': typeof MainBlogIndexRoute
  '/games': typeof MainGamesIndexRoute
  '/labs': typeof MainLabsIndexRoute
  '/projects': typeof MainProjectsIndexRoute
  '/watching': typeof MainWatchingIndexRoute
  '/labs/at-uri/$': typeof MainLabsAtUriSplatRoute
  '/labs/car-explorer/$': typeof MainLabsCarExplorerSplatRoute
  '/labs/css-battles/$date': typeof MainLabsCssBattlesDateRoute
  '/labs/feed/$': typeof MainLabsFeedSplatRoute
  '/labs/lexicon/$nsid': typeof MainLabsLexiconNsidRoute
  '/labs/plc-log/$': typeof MainLabsPlcLogSplatRoute
  '/labs/at-uri': typeof MainLabsAtUriIndexRoute
  '/labs/car-explorer': typeof MainLabsCarExplorerIndexRoute
  '/labs/css-battles': typeof MainLabsCssBattlesIndexRoute
  '/labs/feed': typeof MainLabsFeedIndexRoute
  '/labs/lexicon': typeof MainLabsLexiconIndexRoute
  '/labs/plc-log': typeof MainLabsPlcLogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/design-system': typeof MainDesignSystemRoute
  '/_main/gallery': typeof MainGalleryRoute
  '/_main/music': typeof MainMusicRoute
  '/_main/uses': typeof MainUsesRoute
  '/_main/': typeof MainIndexRoute
  '/_main/blog/$rkey': typeof MainBlogRkeyRoute
  '/_main/games/$rkey': typeof MainGamesRkeyRoute
  '/_main/labs/infinite-canvas': typeof MainLabsInfiniteCanvasRoute
  '/_main/labs/jetstream': typeof MainLabsJetstreamRoute
  '/_main/labs/list-cleaner': typeof MainLabsListCleanerRoute
  '/_main/labs/palette': typeof MainLabsPaletteRoute
  '/_main/labs/pdf-uploader': typeof MainLabsPdfUploaderRoute
  '/_main/labs/screenshot-maker': typeof MainLabsScreenshotMakerRoute
  '/_main/labs/tid': typeof MainLabsTidRoute
  '/_main/labs/verse-reveal': typeof MainLabsVerseRevealRoute
  '/_main/projects/$name': typeof MainProjectsNameRoute
  '/_main/watching/$rkey': typeof MainWatchingRkeyRoute
  '/_main/blog/': typeof MainBlogIndexRoute
  '/_main/games/': typeof MainGamesIndexRoute
  '/_main/labs/': typeof MainLabsIndexRoute
  '/_main/projects/': typeof MainProjectsIndexRoute
  '/_main/watching/': typeof MainWatchingIndexRoute
  '/_main/labs/at-uri/$': typeof MainLabsAtUriSplatRoute
  '/_main/labs/car-explorer/$': typeof MainLabsCarExplorerSplatRoute
  '/_main/labs/css-battles/$date': typeof MainLabsCssBattlesDateRoute
  '/_main/labs/feed/$': typeof MainLabsFeedSplatRoute
  '/_main/labs/lexicon/$nsid': typeof MainLabsLexiconNsidRoute
  '/_main/labs/plc-log/$': typeof MainLabsPlcLogSplatRoute
  '/_main/labs/at-uri/': typeof MainLabsAtUriIndexRoute
  '/_main/labs/car-explorer/': typeof MainLabsCarExplorerIndexRoute
  '/_main/labs/css-battles/': typeof MainLabsCssBattlesIndexRoute
  '/_main/labs/feed/': typeof MainLabsFeedIndexRoute
  '/_main/labs/lexicon/': typeof MainLabsLexiconIndexRoute
  '/_main/labs/plc-log/': typeof MainLabsPlcLogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/gallery'
    | '/music'
    | '/uses'
    | '/blog/$rkey'
    | '/games/$rkey'
    | '/labs/infinite-canvas'
    | '/labs/jetstream'
    | '/labs/list-cleaner'
    | '/labs/palette'
    | '/labs/pdf-uploader'
    | '/labs/screenshot-maker'
    | '/labs/tid'
    | '/labs/verse-reveal'
    | '/projects/$name'
    | '/watching/$rkey'
    | '/blog/'
    | '/games/'
    | '/labs/'
    | '/projects/'
    | '/watching/'
    | '/labs/at-uri/$'
    | '/labs/car-explorer/$'
    | '/labs/css-battles/$date'
    | '/labs/feed/$'
    | '/labs/lexicon/$nsid'
    | '/labs/plc-log/$'
    | '/labs/at-uri/'
    | '/labs/car-explorer/'
    | '/labs/css-battles/'
    | '/labs/feed/'
    | '/labs/lexicon/'
    | '/labs/plc-log/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design-system'
    | '/gallery'
    | '/music'
    | '/uses'
    | '/'
    | '/blog/$rkey'
    | '/games/$rkey'
    | '/labs/infinite-canvas'
    | '/labs/jetstream'
    | '/labs/list-cleaner'
    | '/labs/palette'
    | '/labs/pdf-uploader'
    | '/labs/screenshot-maker'
    | '/labs/tid'
    | '/labs/verse-reveal'
    | '/projects/$name'
    | '/watching/$rkey'
    | '/blog'
    | '/games'
    | '/labs'
    | '/projects'
    | '/watching'
    | '/labs/at-uri/$'
    | '/labs/car-explorer/$'
    | '/labs/css-battles/$date'
    | '/labs/feed/$'
    | '/labs/lexicon/$nsid'
    | '/labs/plc-log/$'
    | '/labs/at-uri'
    | '/labs/car-explorer'
    | '/labs/css-battles'
    | '/labs/feed'
    | '/labs/lexicon'
    | '/labs/plc-log'
  id:
    | '__root__'
    | '/_main'
    | '/_main/design-system'
    | '/_main/gallery'
    | '/_main/music'
    | '/_main/uses'
    | '/_main/'
    | '/_main/blog/$rkey'
    | '/_main/games/$rkey'
    | '/_main/labs/infinite-canvas'
    | '/_main/labs/jetstream'
    | '/_main/labs/list-cleaner'
    | '/_main/labs/palette'
    | '/_main/labs/pdf-uploader'
    | '/_main/labs/screenshot-maker'
    | '/_main/labs/tid'
    | '/_main/labs/verse-reveal'
    | '/_main/projects/$name'
    | '/_main/watching/$rkey'
    | '/_main/blog/'
    | '/_main/games/'
    | '/_main/labs/'
    | '/_main/projects/'
    | '/_main/watching/'
    | '/_main/labs/at-uri/$'
    | '/_main/labs/car-explorer/$'
    | '/_main/labs/css-battles/$date'
    | '/_main/labs/feed/$'
    | '/_main/labs/lexicon/$nsid'
    | '/_main/labs/plc-log/$'
    | '/_main/labs/at-uri/'
    | '/_main/labs/car-explorer/'
    | '/_main/labs/css-battles/'
    | '/_main/labs/feed/'
    | '/_main/labs/lexicon/'
    | '/_main/labs/plc-log/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/uses': {
      id: '/_main/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof MainUsesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/music': {
      id: '/_main/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MainMusicRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/gallery': {
      id: '/_main/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof MainGalleryRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/design-system': {
      id: '/_main/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof MainDesignSystemRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/watching/': {
      id: '/_main/watching/'
      path: '/watching'
      fullPath: '/watching/'
      preLoaderRoute: typeof MainWatchingIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/': {
      id: '/_main/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof MainProjectsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/': {
      id: '/_main/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof MainLabsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/games/': {
      id: '/_main/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof MainGamesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/': {
      id: '/_main/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof MainBlogIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/watching/$rkey': {
      id: '/_main/watching/$rkey'
      path: '/watching/$rkey'
      fullPath: '/watching/$rkey'
      preLoaderRoute: typeof MainWatchingRkeyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/$name': {
      id: '/_main/projects/$name'
      path: '/projects/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof MainProjectsNameRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/verse-reveal': {
      id: '/_main/labs/verse-reveal'
      path: '/labs/verse-reveal'
      fullPath: '/labs/verse-reveal'
      preLoaderRoute: typeof MainLabsVerseRevealRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/tid': {
      id: '/_main/labs/tid'
      path: '/labs/tid'
      fullPath: '/labs/tid'
      preLoaderRoute: typeof MainLabsTidRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/screenshot-maker': {
      id: '/_main/labs/screenshot-maker'
      path: '/labs/screenshot-maker'
      fullPath: '/labs/screenshot-maker'
      preLoaderRoute: typeof MainLabsScreenshotMakerRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/pdf-uploader': {
      id: '/_main/labs/pdf-uploader'
      path: '/labs/pdf-uploader'
      fullPath: '/labs/pdf-uploader'
      preLoaderRoute: typeof MainLabsPdfUploaderRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/palette': {
      id: '/_main/labs/palette'
      path: '/labs/palette'
      fullPath: '/labs/palette'
      preLoaderRoute: typeof MainLabsPaletteRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/list-cleaner': {
      id: '/_main/labs/list-cleaner'
      path: '/labs/list-cleaner'
      fullPath: '/labs/list-cleaner'
      preLoaderRoute: typeof MainLabsListCleanerRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/jetstream': {
      id: '/_main/labs/jetstream'
      path: '/labs/jetstream'
      fullPath: '/labs/jetstream'
      preLoaderRoute: typeof MainLabsJetstreamRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/infinite-canvas': {
      id: '/_main/labs/infinite-canvas'
      path: '/labs/infinite-canvas'
      fullPath: '/labs/infinite-canvas'
      preLoaderRoute: typeof MainLabsInfiniteCanvasRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/games/$rkey': {
      id: '/_main/games/$rkey'
      path: '/games/$rkey'
      fullPath: '/games/$rkey'
      preLoaderRoute: typeof MainGamesRkeyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/$rkey': {
      id: '/_main/blog/$rkey'
      path: '/blog/$rkey'
      fullPath: '/blog/$rkey'
      preLoaderRoute: typeof MainBlogRkeyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/plc-log/': {
      id: '/_main/labs/plc-log/'
      path: '/labs/plc-log'
      fullPath: '/labs/plc-log/'
      preLoaderRoute: typeof MainLabsPlcLogIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/lexicon/': {
      id: '/_main/labs/lexicon/'
      path: '/labs/lexicon'
      fullPath: '/labs/lexicon/'
      preLoaderRoute: typeof MainLabsLexiconIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/feed/': {
      id: '/_main/labs/feed/'
      path: '/labs/feed'
      fullPath: '/labs/feed/'
      preLoaderRoute: typeof MainLabsFeedIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/css-battles/': {
      id: '/_main/labs/css-battles/'
      path: '/labs/css-battles'
      fullPath: '/labs/css-battles/'
      preLoaderRoute: typeof MainLabsCssBattlesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/car-explorer/': {
      id: '/_main/labs/car-explorer/'
      path: '/labs/car-explorer'
      fullPath: '/labs/car-explorer/'
      preLoaderRoute: typeof MainLabsCarExplorerIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/at-uri/': {
      id: '/_main/labs/at-uri/'
      path: '/labs/at-uri'
      fullPath: '/labs/at-uri/'
      preLoaderRoute: typeof MainLabsAtUriIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/plc-log/$': {
      id: '/_main/labs/plc-log/$'
      path: '/labs/plc-log/$'
      fullPath: '/labs/plc-log/$'
      preLoaderRoute: typeof MainLabsPlcLogSplatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/lexicon/$nsid': {
      id: '/_main/labs/lexicon/$nsid'
      path: '/labs/lexicon/$nsid'
      fullPath: '/labs/lexicon/$nsid'
      preLoaderRoute: typeof MainLabsLexiconNsidRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/feed/$': {
      id: '/_main/labs/feed/$'
      path: '/labs/feed/$'
      fullPath: '/labs/feed/$'
      preLoaderRoute: typeof MainLabsFeedSplatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/css-battles/$date': {
      id: '/_main/labs/css-battles/$date'
      path: '/labs/css-battles/$date'
      fullPath: '/labs/css-battles/$date'
      preLoaderRoute: typeof MainLabsCssBattlesDateRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/car-explorer/$': {
      id: '/_main/labs/car-explorer/$'
      path: '/labs/car-explorer/$'
      fullPath: '/labs/car-explorer/$'
      preLoaderRoute: typeof MainLabsCarExplorerSplatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/at-uri/$': {
      id: '/_main/labs/at-uri/$'
      path: '/labs/at-uri/$'
      fullPath: '/labs/at-uri/$'
      preLoaderRoute: typeof MainLabsAtUriSplatRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainDesignSystemRoute: typeof MainDesignSystemRoute
  MainGalleryRoute: typeof MainGalleryRoute
  MainMusicRoute: typeof MainMusicRoute
  MainUsesRoute: typeof MainUsesRoute
  MainIndexRoute: typeof MainIndexRoute
  MainBlogRkeyRoute: typeof MainBlogRkeyRoute
  MainGamesRkeyRoute: typeof MainGamesRkeyRoute
  MainLabsInfiniteCanvasRoute: typeof MainLabsInfiniteCanvasRoute
  MainLabsJetstreamRoute: typeof MainLabsJetstreamRoute
  MainLabsListCleanerRoute: typeof MainLabsListCleanerRoute
  MainLabsPaletteRoute: typeof MainLabsPaletteRoute
  MainLabsPdfUploaderRoute: typeof MainLabsPdfUploaderRoute
  MainLabsScreenshotMakerRoute: typeof MainLabsScreenshotMakerRoute
  MainLabsTidRoute: typeof MainLabsTidRoute
  MainLabsVerseRevealRoute: typeof MainLabsVerseRevealRoute
  MainProjectsNameRoute: typeof MainProjectsNameRoute
  MainWatchingRkeyRoute: typeof MainWatchingRkeyRoute
  MainBlogIndexRoute: typeof MainBlogIndexRoute
  MainGamesIndexRoute: typeof MainGamesIndexRoute
  MainLabsIndexRoute: typeof MainLabsIndexRoute
  MainProjectsIndexRoute: typeof MainProjectsIndexRoute
  MainWatchingIndexRoute: typeof MainWatchingIndexRoute
  MainLabsAtUriSplatRoute: typeof MainLabsAtUriSplatRoute
  MainLabsCarExplorerSplatRoute: typeof MainLabsCarExplorerSplatRoute
  MainLabsCssBattlesDateRoute: typeof MainLabsCssBattlesDateRoute
  MainLabsFeedSplatRoute: typeof MainLabsFeedSplatRoute
  MainLabsLexiconNsidRoute: typeof MainLabsLexiconNsidRoute
  MainLabsPlcLogSplatRoute: typeof MainLabsPlcLogSplatRoute
  MainLabsAtUriIndexRoute: typeof MainLabsAtUriIndexRoute
  MainLabsCarExplorerIndexRoute: typeof MainLabsCarExplorerIndexRoute
  MainLabsCssBattlesIndexRoute: typeof MainLabsCssBattlesIndexRoute
  MainLabsFeedIndexRoute: typeof MainLabsFeedIndexRoute
  MainLabsLexiconIndexRoute: typeof MainLabsLexiconIndexRoute
  MainLabsPlcLogIndexRoute: typeof MainLabsPlcLogIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainDesignSystemRoute: MainDesignSystemRoute,
  MainGalleryRoute: MainGalleryRoute,
  MainMusicRoute: MainMusicRoute,
  MainUsesRoute: MainUsesRoute,
  MainIndexRoute: MainIndexRoute,
  MainBlogRkeyRoute: MainBlogRkeyRoute,
  MainGamesRkeyRoute: MainGamesRkeyRoute,
  MainLabsInfiniteCanvasRoute: MainLabsInfiniteCanvasRoute,
  MainLabsJetstreamRoute: MainLabsJetstreamRoute,
  MainLabsListCleanerRoute: MainLabsListCleanerRoute,
  MainLabsPaletteRoute: MainLabsPaletteRoute,
  MainLabsPdfUploaderRoute: MainLabsPdfUploaderRoute,
  MainLabsScreenshotMakerRoute: MainLabsScreenshotMakerRoute,
  MainLabsTidRoute: MainLabsTidRoute,
  MainLabsVerseRevealRoute: MainLabsVerseRevealRoute,
  MainProjectsNameRoute: MainProjectsNameRoute,
  MainWatchingRkeyRoute: MainWatchingRkeyRoute,
  MainBlogIndexRoute: MainBlogIndexRoute,
  MainGamesIndexRoute: MainGamesIndexRoute,
  MainLabsIndexRoute: MainLabsIndexRoute,
  MainProjectsIndexRoute: MainProjectsIndexRoute,
  MainWatchingIndexRoute: MainWatchingIndexRoute,
  MainLabsAtUriSplatRoute: MainLabsAtUriSplatRoute,
  MainLabsCarExplorerSplatRoute: MainLabsCarExplorerSplatRoute,
  MainLabsCssBattlesDateRoute: MainLabsCssBattlesDateRoute,
  MainLabsFeedSplatRoute: MainLabsFeedSplatRoute,
  MainLabsLexiconNsidRoute: MainLabsLexiconNsidRoute,
  MainLabsPlcLogSplatRoute: MainLabsPlcLogSplatRoute,
  MainLabsAtUriIndexRoute: MainLabsAtUriIndexRoute,
  MainLabsCarExplorerIndexRoute: MainLabsCarExplorerIndexRoute,
  MainLabsCssBattlesIndexRoute: MainLabsCssBattlesIndexRoute,
  MainLabsFeedIndexRoute: MainLabsFeedIndexRoute,
  MainLabsLexiconIndexRoute: MainLabsLexiconIndexRoute,
  MainLabsPlcLogIndexRoute: MainLabsPlcLogIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
