/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as OgSplatRouteImport } from './routes/og/$'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as MainUsesRouteImport } from './routes/_main/uses'
import { Route as MainMusicRouteImport } from './routes/_main/music'
import { Route as MainLibraryRouteImport } from './routes/_main/library'
import { Route as MainHomelabRouteImport } from './routes/_main/homelab'
import { Route as MainHealthRouteImport } from './routes/_main/health'
import { Route as MainGuestbookRouteImport } from './routes/_main/guestbook'
import { Route as MainGlobeRouteImport } from './routes/_main/globe'
import { Route as MainGalleryRouteImport } from './routes/_main/gallery'
import { Route as MainDesignSystemRouteImport } from './routes/_main/design-system'
import { Route as MainBookmarksRouteImport } from './routes/_main/bookmarks'
import { Route as MainAiRouteImport } from './routes/_main/ai'
import { Route as MainWatchingIndexRouteImport } from './routes/_main/watching/index'
import { Route as MainProjectsIndexRouteImport } from './routes/_main/projects/index'
import { Route as MainLabsIndexRouteImport } from './routes/_main/labs/index'
import { Route as MainGamesIndexRouteImport } from './routes/_main/games/index'
import { Route as MainBlogIndexRouteImport } from './routes/_main/blog/index'
import { Route as MainWatchingRkeyRouteImport } from './routes/_main/watching/$rkey'
import { Route as MainProjectsNameRouteImport } from './routes/_main/projects/$name'
import { Route as MainLabsWordleRouteImport } from './routes/_main/labs/wordle'
import { Route as MainLabsWhoisRouteImport } from './routes/_main/labs/whois'
import { Route as MainLabsVerseRevealRouteImport } from './routes/_main/labs/verse-reveal'
import { Route as MainLabsUnitsRouteImport } from './routes/_main/labs/units'
import { Route as MainLabsUnicodeRouteImport } from './routes/_main/labs/unicode'
import { Route as MainLabsUaRouteImport } from './routes/_main/labs/ua'
import { Route as MainLabsTypingRouteImport } from './routes/_main/labs/typing'
import { Route as MainLabsTimestampRouteImport } from './routes/_main/labs/timestamp'
import { Route as MainLabsTidRouteImport } from './routes/_main/labs/tid'
import { Route as MainLabsThreadTreeRouteImport } from './routes/_main/labs/thread-tree'
import { Route as MainLabsTflTubeMapRouteImport } from './routes/_main/labs/tfl-tube-map'
import { Route as MainLabsTflStatusRouteImport } from './routes/_main/labs/tfl-status'
import { Route as MainLabsTflRoadsRouteImport } from './routes/_main/labs/tfl-roads'
import { Route as MainLabsTflCyclesRouteImport } from './routes/_main/labs/tfl-cycles'
import { Route as MainLabsTflArrivalsRouteImport } from './routes/_main/labs/tfl-arrivals'
import { Route as MainLabsTflAirRouteImport } from './routes/_main/labs/tfl-air'
import { Route as MainLabsTerminalRouteImport } from './routes/_main/labs/terminal'
import { Route as MainLabsSubnetRouteImport } from './routes/_main/labs/subnet'
import { Route as MainLabsSpectrogramRouteImport } from './routes/_main/labs/spectrogram'
import { Route as MainLabsSnakeRouteImport } from './routes/_main/labs/snake'
import { Route as MainLabsScreenshotMakerRouteImport } from './routes/_main/labs/screenshot-maker'
import { Route as MainLabsSchemaRouteImport } from './routes/_main/labs/schema'
import { Route as MainLabsRegexRouteImport } from './routes/_main/labs/regex'
import { Route as MainLabsPngChunksRouteImport } from './routes/_main/labs/png-chunks'
import { Route as MainLabsPeriodicRouteImport } from './routes/_main/labs/periodic'
import { Route as MainLabsPdsHealthRouteImport } from './routes/_main/labs/pds-health'
import { Route as MainLabsPdfUploaderRouteImport } from './routes/_main/labs/pdf-uploader'
import { Route as MainLabsPasswordRouteImport } from './routes/_main/labs/password'
import { Route as MainLabsPaletteRouteImport } from './routes/_main/labs/palette'
import { Route as MainLabsOgPreviewRouteImport } from './routes/_main/labs/og-preview'
import { Route as MainLabsMpRouteImport } from './routes/_main/labs/mp'
import { Route as MainLabsMatrixRouteImport } from './routes/_main/labs/matrix'
import { Route as MainLabsListCleanerRouteImport } from './routes/_main/labs/list-cleaner'
import { Route as MainLabsLightningRouteImport } from './routes/_main/labs/lightning'
import { Route as MainLabsLifeRouteImport } from './routes/_main/labs/life'
import { Route as MainLabsLexiconValidatorRouteImport } from './routes/_main/labs/lexicon-validator'
import { Route as MainLabsJwtRouteImport } from './routes/_main/labs/jwt'
import { Route as MainLabsJsonRouteImport } from './routes/_main/labs/json'
import { Route as MainLabsJetstreamRouteImport } from './routes/_main/labs/jetstream'
import { Route as MainLabsIssRouteImport } from './routes/_main/labs/iss'
import { Route as MainLabsInfiniteCanvasRouteImport } from './routes/_main/labs/infinite-canvas'
import { Route as MainLabsIdsRouteImport } from './routes/_main/labs/ids'
import { Route as MainLabsHygieneRouteImport } from './routes/_main/labs/hygiene'
import { Route as MainLabsHttpStatusRouteImport } from './routes/_main/labs/http-status'
import { Route as MainLabsHttpHeadersRouteImport } from './routes/_main/labs/http-headers'
import { Route as MainLabsHexDumpRouteImport } from './routes/_main/labs/hex-dump'
import { Route as MainLabsHashRouteImport } from './routes/_main/labs/hash'
import { Route as MainLabsHandleSniperRouteImport } from './routes/_main/labs/handle-sniper'
import { Route as MainLabsFirehoseStatsRouteImport } from './routes/_main/labs/firehose-stats'
import { Route as MainLabsFingerprintRouteImport } from './routes/_main/labs/fingerprint'
import { Route as MainLabsExifRouteImport } from './routes/_main/labs/exif'
import { Route as MainLabsEncodeRouteImport } from './routes/_main/labs/encode'
import { Route as MainLabsDnsRouteImport } from './routes/_main/labs/dns'
import { Route as MainLabsDistRouteImport } from './routes/_main/labs/dist'
import { Route as MainLabsDiffRouteImport } from './routes/_main/labs/diff'
import { Route as MainLabsDidLogRouteImport } from './routes/_main/labs/did-log'
import { Route as MainLabsCurlRouteImport } from './routes/_main/labs/curl'
import { Route as MainLabsCsvRouteImport } from './routes/_main/labs/csv'
import { Route as MainLabsCryptoRouteImport } from './routes/_main/labs/crypto'
import { Route as MainLabsCronRouteImport } from './routes/_main/labs/cron'
import { Route as MainLabsCrimeRouteImport } from './routes/_main/labs/crime'
import { Route as MainLabsColourRouteImport } from './routes/_main/labs/colour'
import { Route as MainLabsCertsRouteImport } from './routes/_main/labs/certs'
import { Route as MainLabsCaseRouteImport } from './routes/_main/labs/case'
import { Route as MainLabsBskyComposerRouteImport } from './routes/_main/labs/bsky-composer'
import { Route as MainLabsBrowserRouteImport } from './routes/_main/labs/browser'
import { Route as MainLabsAsciiRouteImport } from './routes/_main/labs/ascii'
import { Route as MainGamesRkeyRouteImport } from './routes/_main/games/$rkey'
import { Route as MainBlogRkeyRouteImport } from './routes/_main/blog/$rkey'
import { Route as MainLabsYearInReviewIndexRouteImport } from './routes/_main/labs/year-in-review/index'
import { Route as MainLabsPlcLogIndexRouteImport } from './routes/_main/labs/plc-log/index'
import { Route as MainLabsLexiconIndexRouteImport } from './routes/_main/labs/lexicon/index'
import { Route as MainLabsFeedIndexRouteImport } from './routes/_main/labs/feed/index'
import { Route as MainLabsCssBattlesIndexRouteImport } from './routes/_main/labs/css-battles/index'
import { Route as MainLabsCarExplorerIndexRouteImport } from './routes/_main/labs/car-explorer/index'
import { Route as MainLabsAtUriIndexRouteImport } from './routes/_main/labs/at-uri/index'
import { Route as MainPokedexRkeyPokeIdRouteImport } from './routes/_main/pokedex/$rkey/$pokeId'
import { Route as MainLabsPlcLogSplatRouteImport } from './routes/_main/labs/plc-log/$'
import { Route as MainLabsLexiconNsidRouteImport } from './routes/_main/labs/lexicon/$nsid'
import { Route as MainLabsFeedSplatRouteImport } from './routes/_main/labs/feed/$'
import { Route as MainLabsCssBattlesDateRouteImport } from './routes/_main/labs/css-battles/$date'
import { Route as MainLabsCarExplorerSplatRouteImport } from './routes/_main/labs/car-explorer/$'
import { Route as MainLabsAtUriSplatRouteImport } from './routes/_main/labs/at-uri/$'
import { Route as MainLabsYearInReviewHandleYearRouteImport } from './routes/_main/labs/year-in-review/$handle/$year'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const OgSplatRoute = OgSplatRouteImport.update({
  id: '/og/$',
  path: '/og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MainUsesRoute = MainUsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => MainRoute,
} as any)
const MainMusicRoute = MainMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => MainRoute,
} as any)
const MainLibraryRoute = MainLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => MainRoute,
} as any)
const MainHomelabRoute = MainHomelabRouteImport.update({
  id: '/homelab',
  path: '/homelab',
  getParentRoute: () => MainRoute,
} as any)
const MainHealthRoute = MainHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => MainRoute,
} as any)
const MainGuestbookRoute = MainGuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => MainRoute,
} as any)
const MainGlobeRoute = MainGlobeRouteImport.update({
  id: '/globe',
  path: '/globe',
  getParentRoute: () => MainRoute,
} as any)
const MainGalleryRoute = MainGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => MainRoute,
} as any)
const MainDesignSystemRoute = MainDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => MainRoute,
} as any)
const MainBookmarksRoute = MainBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => MainRoute,
} as any)
const MainAiRoute = MainAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => MainRoute,
} as any)
const MainWatchingIndexRoute = MainWatchingIndexRouteImport.update({
  id: '/watching/',
  path: '/watching/',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsIndexRoute = MainProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsIndexRoute = MainLabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => MainRoute,
} as any)
const MainGamesIndexRoute = MainGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogIndexRoute = MainBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => MainRoute,
} as any)
const MainWatchingRkeyRoute = MainWatchingRkeyRouteImport.update({
  id: '/watching/$rkey',
  path: '/watching/$rkey',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsNameRoute = MainProjectsNameRouteImport.update({
  id: '/projects/$name',
  path: '/projects/$name',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsWordleRoute = MainLabsWordleRouteImport.update({
  id: '/labs/wordle',
  path: '/labs/wordle',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsWhoisRoute = MainLabsWhoisRouteImport.update({
  id: '/labs/whois',
  path: '/labs/whois',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsVerseRevealRoute = MainLabsVerseRevealRouteImport.update({
  id: '/labs/verse-reveal',
  path: '/labs/verse-reveal',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsUnitsRoute = MainLabsUnitsRouteImport.update({
  id: '/labs/units',
  path: '/labs/units',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsUnicodeRoute = MainLabsUnicodeRouteImport.update({
  id: '/labs/unicode',
  path: '/labs/unicode',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsUaRoute = MainLabsUaRouteImport.update({
  id: '/labs/ua',
  path: '/labs/ua',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsTypingRoute = MainLabsTypingRouteImport.update({
  id: '/labs/typing',
  path: '/labs/typing',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsTimestampRoute = MainLabsTimestampRouteImport.update({
  id: '/labs/timestamp',
  path: '/labs/timestamp',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsTidRoute = MainLabsTidRouteImport.update({
  id: '/labs/tid',
  path: '/labs/tid',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsThreadTreeRoute = MainLabsThreadTreeRouteImport.update({
  id: '/labs/thread-tree',
  path: '/labs/thread-tree',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsTflTubeMapRoute = MainLabsTflTubeMapRouteImport.update({
  id: '/labs/tfl-tube-map',
  path: '/labs/tfl-tube-map',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsTflStatusRoute = MainLabsTflStatusRouteImport.update({
  id: '/labs/tfl-status',
  path: '/labs/tfl-status',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsTflRoadsRoute = MainLabsTflRoadsRouteImport.update({
  id: '/labs/tfl-roads',
  path: '/labs/tfl-roads',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsTflCyclesRoute = MainLabsTflCyclesRouteImport.update({
  id: '/labs/tfl-cycles',
  path: '/labs/tfl-cycles',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsTflArrivalsRoute = MainLabsTflArrivalsRouteImport.update({
  id: '/labs/tfl-arrivals',
  path: '/labs/tfl-arrivals',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsTflAirRoute = MainLabsTflAirRouteImport.update({
  id: '/labs/tfl-air',
  path: '/labs/tfl-air',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsTerminalRoute = MainLabsTerminalRouteImport.update({
  id: '/labs/terminal',
  path: '/labs/terminal',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsSubnetRoute = MainLabsSubnetRouteImport.update({
  id: '/labs/subnet',
  path: '/labs/subnet',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsSpectrogramRoute = MainLabsSpectrogramRouteImport.update({
  id: '/labs/spectrogram',
  path: '/labs/spectrogram',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsSnakeRoute = MainLabsSnakeRouteImport.update({
  id: '/labs/snake',
  path: '/labs/snake',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsScreenshotMakerRoute = MainLabsScreenshotMakerRouteImport.update({
  id: '/labs/screenshot-maker',
  path: '/labs/screenshot-maker',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsSchemaRoute = MainLabsSchemaRouteImport.update({
  id: '/labs/schema',
  path: '/labs/schema',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsRegexRoute = MainLabsRegexRouteImport.update({
  id: '/labs/regex',
  path: '/labs/regex',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsPngChunksRoute = MainLabsPngChunksRouteImport.update({
  id: '/labs/png-chunks',
  path: '/labs/png-chunks',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsPeriodicRoute = MainLabsPeriodicRouteImport.update({
  id: '/labs/periodic',
  path: '/labs/periodic',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsPdsHealthRoute = MainLabsPdsHealthRouteImport.update({
  id: '/labs/pds-health',
  path: '/labs/pds-health',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsPdfUploaderRoute = MainLabsPdfUploaderRouteImport.update({
  id: '/labs/pdf-uploader',
  path: '/labs/pdf-uploader',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsPasswordRoute = MainLabsPasswordRouteImport.update({
  id: '/labs/password',
  path: '/labs/password',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsPaletteRoute = MainLabsPaletteRouteImport.update({
  id: '/labs/palette',
  path: '/labs/palette',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsOgPreviewRoute = MainLabsOgPreviewRouteImport.update({
  id: '/labs/og-preview',
  path: '/labs/og-preview',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsMpRoute = MainLabsMpRouteImport.update({
  id: '/labs/mp',
  path: '/labs/mp',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsMatrixRoute = MainLabsMatrixRouteImport.update({
  id: '/labs/matrix',
  path: '/labs/matrix',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsListCleanerRoute = MainLabsListCleanerRouteImport.update({
  id: '/labs/list-cleaner',
  path: '/labs/list-cleaner',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsLightningRoute = MainLabsLightningRouteImport.update({
  id: '/labs/lightning',
  path: '/labs/lightning',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsLifeRoute = MainLabsLifeRouteImport.update({
  id: '/labs/life',
  path: '/labs/life',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsLexiconValidatorRoute =
  MainLabsLexiconValidatorRouteImport.update({
    id: '/labs/lexicon-validator',
    path: '/labs/lexicon-validator',
    getParentRoute: () => MainRoute,
  } as any)
const MainLabsJwtRoute = MainLabsJwtRouteImport.update({
  id: '/labs/jwt',
  path: '/labs/jwt',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsJsonRoute = MainLabsJsonRouteImport.update({
  id: '/labs/json',
  path: '/labs/json',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsJetstreamRoute = MainLabsJetstreamRouteImport.update({
  id: '/labs/jetstream',
  path: '/labs/jetstream',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsIssRoute = MainLabsIssRouteImport.update({
  id: '/labs/iss',
  path: '/labs/iss',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsInfiniteCanvasRoute = MainLabsInfiniteCanvasRouteImport.update({
  id: '/labs/infinite-canvas',
  path: '/labs/infinite-canvas',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsIdsRoute = MainLabsIdsRouteImport.update({
  id: '/labs/ids',
  path: '/labs/ids',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsHygieneRoute = MainLabsHygieneRouteImport.update({
  id: '/labs/hygiene',
  path: '/labs/hygiene',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsHttpStatusRoute = MainLabsHttpStatusRouteImport.update({
  id: '/labs/http-status',
  path: '/labs/http-status',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsHttpHeadersRoute = MainLabsHttpHeadersRouteImport.update({
  id: '/labs/http-headers',
  path: '/labs/http-headers',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsHexDumpRoute = MainLabsHexDumpRouteImport.update({
  id: '/labs/hex-dump',
  path: '/labs/hex-dump',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsHashRoute = MainLabsHashRouteImport.update({
  id: '/labs/hash',
  path: '/labs/hash',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsHandleSniperRoute = MainLabsHandleSniperRouteImport.update({
  id: '/labs/handle-sniper',
  path: '/labs/handle-sniper',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsFirehoseStatsRoute = MainLabsFirehoseStatsRouteImport.update({
  id: '/labs/firehose-stats',
  path: '/labs/firehose-stats',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsFingerprintRoute = MainLabsFingerprintRouteImport.update({
  id: '/labs/fingerprint',
  path: '/labs/fingerprint',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsExifRoute = MainLabsExifRouteImport.update({
  id: '/labs/exif',
  path: '/labs/exif',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsEncodeRoute = MainLabsEncodeRouteImport.update({
  id: '/labs/encode',
  path: '/labs/encode',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsDnsRoute = MainLabsDnsRouteImport.update({
  id: '/labs/dns',
  path: '/labs/dns',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsDistRoute = MainLabsDistRouteImport.update({
  id: '/labs/dist',
  path: '/labs/dist',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsDiffRoute = MainLabsDiffRouteImport.update({
  id: '/labs/diff',
  path: '/labs/diff',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsDidLogRoute = MainLabsDidLogRouteImport.update({
  id: '/labs/did-log',
  path: '/labs/did-log',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCurlRoute = MainLabsCurlRouteImport.update({
  id: '/labs/curl',
  path: '/labs/curl',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCsvRoute = MainLabsCsvRouteImport.update({
  id: '/labs/csv',
  path: '/labs/csv',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCryptoRoute = MainLabsCryptoRouteImport.update({
  id: '/labs/crypto',
  path: '/labs/crypto',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCronRoute = MainLabsCronRouteImport.update({
  id: '/labs/cron',
  path: '/labs/cron',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCrimeRoute = MainLabsCrimeRouteImport.update({
  id: '/labs/crime',
  path: '/labs/crime',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsColourRoute = MainLabsColourRouteImport.update({
  id: '/labs/colour',
  path: '/labs/colour',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCertsRoute = MainLabsCertsRouteImport.update({
  id: '/labs/certs',
  path: '/labs/certs',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCaseRoute = MainLabsCaseRouteImport.update({
  id: '/labs/case',
  path: '/labs/case',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsBskyComposerRoute = MainLabsBskyComposerRouteImport.update({
  id: '/labs/bsky-composer',
  path: '/labs/bsky-composer',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsBrowserRoute = MainLabsBrowserRouteImport.update({
  id: '/labs/browser',
  path: '/labs/browser',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsAsciiRoute = MainLabsAsciiRouteImport.update({
  id: '/labs/ascii',
  path: '/labs/ascii',
  getParentRoute: () => MainRoute,
} as any)
const MainGamesRkeyRoute = MainGamesRkeyRouteImport.update({
  id: '/games/$rkey',
  path: '/games/$rkey',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogRkeyRoute = MainBlogRkeyRouteImport.update({
  id: '/blog/$rkey',
  path: '/blog/$rkey',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsYearInReviewIndexRoute =
  MainLabsYearInReviewIndexRouteImport.update({
    id: '/labs/year-in-review/',
    path: '/labs/year-in-review/',
    getParentRoute: () => MainRoute,
  } as any)
const MainLabsPlcLogIndexRoute = MainLabsPlcLogIndexRouteImport.update({
  id: '/labs/plc-log/',
  path: '/labs/plc-log/',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsLexiconIndexRoute = MainLabsLexiconIndexRouteImport.update({
  id: '/labs/lexicon/',
  path: '/labs/lexicon/',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsFeedIndexRoute = MainLabsFeedIndexRouteImport.update({
  id: '/labs/feed/',
  path: '/labs/feed/',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCssBattlesIndexRoute = MainLabsCssBattlesIndexRouteImport.update({
  id: '/labs/css-battles/',
  path: '/labs/css-battles/',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCarExplorerIndexRoute =
  MainLabsCarExplorerIndexRouteImport.update({
    id: '/labs/car-explorer/',
    path: '/labs/car-explorer/',
    getParentRoute: () => MainRoute,
  } as any)
const MainLabsAtUriIndexRoute = MainLabsAtUriIndexRouteImport.update({
  id: '/labs/at-uri/',
  path: '/labs/at-uri/',
  getParentRoute: () => MainRoute,
} as any)
const MainPokedexRkeyPokeIdRoute = MainPokedexRkeyPokeIdRouteImport.update({
  id: '/pokedex/$rkey/$pokeId',
  path: '/pokedex/$rkey/$pokeId',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsPlcLogSplatRoute = MainLabsPlcLogSplatRouteImport.update({
  id: '/labs/plc-log/$',
  path: '/labs/plc-log/$',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsLexiconNsidRoute = MainLabsLexiconNsidRouteImport.update({
  id: '/labs/lexicon/$nsid',
  path: '/labs/lexicon/$nsid',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsFeedSplatRoute = MainLabsFeedSplatRouteImport.update({
  id: '/labs/feed/$',
  path: '/labs/feed/$',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCssBattlesDateRoute = MainLabsCssBattlesDateRouteImport.update({
  id: '/labs/css-battles/$date',
  path: '/labs/css-battles/$date',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCarExplorerSplatRoute =
  MainLabsCarExplorerSplatRouteImport.update({
    id: '/labs/car-explorer/$',
    path: '/labs/car-explorer/$',
    getParentRoute: () => MainRoute,
  } as any)
const MainLabsAtUriSplatRoute = MainLabsAtUriSplatRouteImport.update({
  id: '/labs/at-uri/$',
  path: '/labs/at-uri/$',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsYearInReviewHandleYearRoute =
  MainLabsYearInReviewHandleYearRouteImport.update({
    id: '/labs/year-in-review/$handle/$year',
    path: '/labs/year-in-review/$handle/$year',
    getParentRoute: () => MainRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof MainAiRoute
  '/bookmarks': typeof MainBookmarksRoute
  '/design-system': typeof MainDesignSystemRoute
  '/gallery': typeof MainGalleryRoute
  '/globe': typeof MainGlobeRoute
  '/guestbook': typeof MainGuestbookRoute
  '/health': typeof MainHealthRoute
  '/homelab': typeof MainHomelabRoute
  '/library': typeof MainLibraryRoute
  '/music': typeof MainMusicRoute
  '/uses': typeof MainUsesRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/og/$': typeof OgSplatRoute
  '/blog/$rkey': typeof MainBlogRkeyRoute
  '/games/$rkey': typeof MainGamesRkeyRoute
  '/labs/ascii': typeof MainLabsAsciiRoute
  '/labs/browser': typeof MainLabsBrowserRoute
  '/labs/bsky-composer': typeof MainLabsBskyComposerRoute
  '/labs/case': typeof MainLabsCaseRoute
  '/labs/certs': typeof MainLabsCertsRoute
  '/labs/colour': typeof MainLabsColourRoute
  '/labs/crime': typeof MainLabsCrimeRoute
  '/labs/cron': typeof MainLabsCronRoute
  '/labs/crypto': typeof MainLabsCryptoRoute
  '/labs/csv': typeof MainLabsCsvRoute
  '/labs/curl': typeof MainLabsCurlRoute
  '/labs/did-log': typeof MainLabsDidLogRoute
  '/labs/diff': typeof MainLabsDiffRoute
  '/labs/dist': typeof MainLabsDistRoute
  '/labs/dns': typeof MainLabsDnsRoute
  '/labs/encode': typeof MainLabsEncodeRoute
  '/labs/exif': typeof MainLabsExifRoute
  '/labs/fingerprint': typeof MainLabsFingerprintRoute
  '/labs/firehose-stats': typeof MainLabsFirehoseStatsRoute
  '/labs/handle-sniper': typeof MainLabsHandleSniperRoute
  '/labs/hash': typeof MainLabsHashRoute
  '/labs/hex-dump': typeof MainLabsHexDumpRoute
  '/labs/http-headers': typeof MainLabsHttpHeadersRoute
  '/labs/http-status': typeof MainLabsHttpStatusRoute
  '/labs/hygiene': typeof MainLabsHygieneRoute
  '/labs/ids': typeof MainLabsIdsRoute
  '/labs/infinite-canvas': typeof MainLabsInfiniteCanvasRoute
  '/labs/iss': typeof MainLabsIssRoute
  '/labs/jetstream': typeof MainLabsJetstreamRoute
  '/labs/json': typeof MainLabsJsonRoute
  '/labs/jwt': typeof MainLabsJwtRoute
  '/labs/lexicon-validator': typeof MainLabsLexiconValidatorRoute
  '/labs/life': typeof MainLabsLifeRoute
  '/labs/lightning': typeof MainLabsLightningRoute
  '/labs/list-cleaner': typeof MainLabsListCleanerRoute
  '/labs/matrix': typeof MainLabsMatrixRoute
  '/labs/mp': typeof MainLabsMpRoute
  '/labs/og-preview': typeof MainLabsOgPreviewRoute
  '/labs/palette': typeof MainLabsPaletteRoute
  '/labs/password': typeof MainLabsPasswordRoute
  '/labs/pdf-uploader': typeof MainLabsPdfUploaderRoute
  '/labs/pds-health': typeof MainLabsPdsHealthRoute
  '/labs/periodic': typeof MainLabsPeriodicRoute
  '/labs/png-chunks': typeof MainLabsPngChunksRoute
  '/labs/regex': typeof MainLabsRegexRoute
  '/labs/schema': typeof MainLabsSchemaRoute
  '/labs/screenshot-maker': typeof MainLabsScreenshotMakerRoute
  '/labs/snake': typeof MainLabsSnakeRoute
  '/labs/spectrogram': typeof MainLabsSpectrogramRoute
  '/labs/subnet': typeof MainLabsSubnetRoute
  '/labs/terminal': typeof MainLabsTerminalRoute
  '/labs/tfl-air': typeof MainLabsTflAirRoute
  '/labs/tfl-arrivals': typeof MainLabsTflArrivalsRoute
  '/labs/tfl-cycles': typeof MainLabsTflCyclesRoute
  '/labs/tfl-roads': typeof MainLabsTflRoadsRoute
  '/labs/tfl-status': typeof MainLabsTflStatusRoute
  '/labs/tfl-tube-map': typeof MainLabsTflTubeMapRoute
  '/labs/thread-tree': typeof MainLabsThreadTreeRoute
  '/labs/tid': typeof MainLabsTidRoute
  '/labs/timestamp': typeof MainLabsTimestampRoute
  '/labs/typing': typeof MainLabsTypingRoute
  '/labs/ua': typeof MainLabsUaRoute
  '/labs/unicode': typeof MainLabsUnicodeRoute
  '/labs/units': typeof MainLabsUnitsRoute
  '/labs/verse-reveal': typeof MainLabsVerseRevealRoute
  '/labs/whois': typeof MainLabsWhoisRoute
  '/labs/wordle': typeof MainLabsWordleRoute
  '/projects/$name': typeof MainProjectsNameRoute
  '/watching/$rkey': typeof MainWatchingRkeyRoute
  '/blog/': typeof MainBlogIndexRoute
  '/games/': typeof MainGamesIndexRoute
  '/labs/': typeof MainLabsIndexRoute
  '/projects/': typeof MainProjectsIndexRoute
  '/watching/': typeof MainWatchingIndexRoute
  '/labs/at-uri/$': typeof MainLabsAtUriSplatRoute
  '/labs/car-explorer/$': typeof MainLabsCarExplorerSplatRoute
  '/labs/css-battles/$date': typeof MainLabsCssBattlesDateRoute
  '/labs/feed/$': typeof MainLabsFeedSplatRoute
  '/labs/lexicon/$nsid': typeof MainLabsLexiconNsidRoute
  '/labs/plc-log/$': typeof MainLabsPlcLogSplatRoute
  '/pokedex/$rkey/$pokeId': typeof MainPokedexRkeyPokeIdRoute
  '/labs/at-uri/': typeof MainLabsAtUriIndexRoute
  '/labs/car-explorer/': typeof MainLabsCarExplorerIndexRoute
  '/labs/css-battles/': typeof MainLabsCssBattlesIndexRoute
  '/labs/feed/': typeof MainLabsFeedIndexRoute
  '/labs/lexicon/': typeof MainLabsLexiconIndexRoute
  '/labs/plc-log/': typeof MainLabsPlcLogIndexRoute
  '/labs/year-in-review/': typeof MainLabsYearInReviewIndexRoute
  '/labs/year-in-review/$handle/$year': typeof MainLabsYearInReviewHandleYearRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof MainAiRoute
  '/bookmarks': typeof MainBookmarksRoute
  '/design-system': typeof MainDesignSystemRoute
  '/gallery': typeof MainGalleryRoute
  '/globe': typeof MainGlobeRoute
  '/guestbook': typeof MainGuestbookRoute
  '/health': typeof MainHealthRoute
  '/homelab': typeof MainHomelabRoute
  '/library': typeof MainLibraryRoute
  '/music': typeof MainMusicRoute
  '/uses': typeof MainUsesRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/og/$': typeof OgSplatRoute
  '/': typeof MainIndexRoute
  '/blog/$rkey': typeof MainBlogRkeyRoute
  '/games/$rkey': typeof MainGamesRkeyRoute
  '/labs/ascii': typeof MainLabsAsciiRoute
  '/labs/browser': typeof MainLabsBrowserRoute
  '/labs/bsky-composer': typeof MainLabsBskyComposerRoute
  '/labs/case': typeof MainLabsCaseRoute
  '/labs/certs': typeof MainLabsCertsRoute
  '/labs/colour': typeof MainLabsColourRoute
  '/labs/crime': typeof MainLabsCrimeRoute
  '/labs/cron': typeof MainLabsCronRoute
  '/labs/crypto': typeof MainLabsCryptoRoute
  '/labs/csv': typeof MainLabsCsvRoute
  '/labs/curl': typeof MainLabsCurlRoute
  '/labs/did-log': typeof MainLabsDidLogRoute
  '/labs/diff': typeof MainLabsDiffRoute
  '/labs/dist': typeof MainLabsDistRoute
  '/labs/dns': typeof MainLabsDnsRoute
  '/labs/encode': typeof MainLabsEncodeRoute
  '/labs/exif': typeof MainLabsExifRoute
  '/labs/fingerprint': typeof MainLabsFingerprintRoute
  '/labs/firehose-stats': typeof MainLabsFirehoseStatsRoute
  '/labs/handle-sniper': typeof MainLabsHandleSniperRoute
  '/labs/hash': typeof MainLabsHashRoute
  '/labs/hex-dump': typeof MainLabsHexDumpRoute
  '/labs/http-headers': typeof MainLabsHttpHeadersRoute
  '/labs/http-status': typeof MainLabsHttpStatusRoute
  '/labs/hygiene': typeof MainLabsHygieneRoute
  '/labs/ids': typeof MainLabsIdsRoute
  '/labs/infinite-canvas': typeof MainLabsInfiniteCanvasRoute
  '/labs/iss': typeof MainLabsIssRoute
  '/labs/jetstream': typeof MainLabsJetstreamRoute
  '/labs/json': typeof MainLabsJsonRoute
  '/labs/jwt': typeof MainLabsJwtRoute
  '/labs/lexicon-validator': typeof MainLabsLexiconValidatorRoute
  '/labs/life': typeof MainLabsLifeRoute
  '/labs/lightning': typeof MainLabsLightningRoute
  '/labs/list-cleaner': typeof MainLabsListCleanerRoute
  '/labs/matrix': typeof MainLabsMatrixRoute
  '/labs/mp': typeof MainLabsMpRoute
  '/labs/og-preview': typeof MainLabsOgPreviewRoute
  '/labs/palette': typeof MainLabsPaletteRoute
  '/labs/password': typeof MainLabsPasswordRoute
  '/labs/pdf-uploader': typeof MainLabsPdfUploaderRoute
  '/labs/pds-health': typeof MainLabsPdsHealthRoute
  '/labs/periodic': typeof MainLabsPeriodicRoute
  '/labs/png-chunks': typeof MainLabsPngChunksRoute
  '/labs/regex': typeof MainLabsRegexRoute
  '/labs/schema': typeof MainLabsSchemaRoute
  '/labs/screenshot-maker': typeof MainLabsScreenshotMakerRoute
  '/labs/snake': typeof MainLabsSnakeRoute
  '/labs/spectrogram': typeof MainLabsSpectrogramRoute
  '/labs/subnet': typeof MainLabsSubnetRoute
  '/labs/terminal': typeof MainLabsTerminalRoute
  '/labs/tfl-air': typeof MainLabsTflAirRoute
  '/labs/tfl-arrivals': typeof MainLabsTflArrivalsRoute
  '/labs/tfl-cycles': typeof MainLabsTflCyclesRoute
  '/labs/tfl-roads': typeof MainLabsTflRoadsRoute
  '/labs/tfl-status': typeof MainLabsTflStatusRoute
  '/labs/tfl-tube-map': typeof MainLabsTflTubeMapRoute
  '/labs/thread-tree': typeof MainLabsThreadTreeRoute
  '/labs/tid': typeof MainLabsTidRoute
  '/labs/timestamp': typeof MainLabsTimestampRoute
  '/labs/typing': typeof MainLabsTypingRoute
  '/labs/ua': typeof MainLabsUaRoute
  '/labs/unicode': typeof MainLabsUnicodeRoute
  '/labs/units': typeof MainLabsUnitsRoute
  '/labs/verse-reveal': typeof MainLabsVerseRevealRoute
  '/labs/whois': typeof MainLabsWhoisRoute
  '/labs/wordle': typeof MainLabsWordleRoute
  '/projects/$name': typeof MainProjectsNameRoute
  '/watching/$rkey': typeof MainWatchingRkeyRoute
  '/blog': typeof MainBlogIndexRoute
  '/games': typeof MainGamesIndexRoute
  '/labs': typeof MainLabsIndexRoute
  '/projects': typeof MainProjectsIndexRoute
  '/watching': typeof MainWatchingIndexRoute
  '/labs/at-uri/$': typeof MainLabsAtUriSplatRoute
  '/labs/car-explorer/$': typeof MainLabsCarExplorerSplatRoute
  '/labs/css-battles/$date': typeof MainLabsCssBattlesDateRoute
  '/labs/feed/$': typeof MainLabsFeedSplatRoute
  '/labs/lexicon/$nsid': typeof MainLabsLexiconNsidRoute
  '/labs/plc-log/$': typeof MainLabsPlcLogSplatRoute
  '/pokedex/$rkey/$pokeId': typeof MainPokedexRkeyPokeIdRoute
  '/labs/at-uri': typeof MainLabsAtUriIndexRoute
  '/labs/car-explorer': typeof MainLabsCarExplorerIndexRoute
  '/labs/css-battles': typeof MainLabsCssBattlesIndexRoute
  '/labs/feed': typeof MainLabsFeedIndexRoute
  '/labs/lexicon': typeof MainLabsLexiconIndexRoute
  '/labs/plc-log': typeof MainLabsPlcLogIndexRoute
  '/labs/year-in-review': typeof MainLabsYearInReviewIndexRoute
  '/labs/year-in-review/$handle/$year': typeof MainLabsYearInReviewHandleYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_main/ai': typeof MainAiRoute
  '/_main/bookmarks': typeof MainBookmarksRoute
  '/_main/design-system': typeof MainDesignSystemRoute
  '/_main/gallery': typeof MainGalleryRoute
  '/_main/globe': typeof MainGlobeRoute
  '/_main/guestbook': typeof MainGuestbookRoute
  '/_main/health': typeof MainHealthRoute
  '/_main/homelab': typeof MainHomelabRoute
  '/_main/library': typeof MainLibraryRoute
  '/_main/music': typeof MainMusicRoute
  '/_main/uses': typeof MainUsesRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/og/$': typeof OgSplatRoute
  '/_main/': typeof MainIndexRoute
  '/_main/blog/$rkey': typeof MainBlogRkeyRoute
  '/_main/games/$rkey': typeof MainGamesRkeyRoute
  '/_main/labs/ascii': typeof MainLabsAsciiRoute
  '/_main/labs/browser': typeof MainLabsBrowserRoute
  '/_main/labs/bsky-composer': typeof MainLabsBskyComposerRoute
  '/_main/labs/case': typeof MainLabsCaseRoute
  '/_main/labs/certs': typeof MainLabsCertsRoute
  '/_main/labs/colour': typeof MainLabsColourRoute
  '/_main/labs/crime': typeof MainLabsCrimeRoute
  '/_main/labs/cron': typeof MainLabsCronRoute
  '/_main/labs/crypto': typeof MainLabsCryptoRoute
  '/_main/labs/csv': typeof MainLabsCsvRoute
  '/_main/labs/curl': typeof MainLabsCurlRoute
  '/_main/labs/did-log': typeof MainLabsDidLogRoute
  '/_main/labs/diff': typeof MainLabsDiffRoute
  '/_main/labs/dist': typeof MainLabsDistRoute
  '/_main/labs/dns': typeof MainLabsDnsRoute
  '/_main/labs/encode': typeof MainLabsEncodeRoute
  '/_main/labs/exif': typeof MainLabsExifRoute
  '/_main/labs/fingerprint': typeof MainLabsFingerprintRoute
  '/_main/labs/firehose-stats': typeof MainLabsFirehoseStatsRoute
  '/_main/labs/handle-sniper': typeof MainLabsHandleSniperRoute
  '/_main/labs/hash': typeof MainLabsHashRoute
  '/_main/labs/hex-dump': typeof MainLabsHexDumpRoute
  '/_main/labs/http-headers': typeof MainLabsHttpHeadersRoute
  '/_main/labs/http-status': typeof MainLabsHttpStatusRoute
  '/_main/labs/hygiene': typeof MainLabsHygieneRoute
  '/_main/labs/ids': typeof MainLabsIdsRoute
  '/_main/labs/infinite-canvas': typeof MainLabsInfiniteCanvasRoute
  '/_main/labs/iss': typeof MainLabsIssRoute
  '/_main/labs/jetstream': typeof MainLabsJetstreamRoute
  '/_main/labs/json': typeof MainLabsJsonRoute
  '/_main/labs/jwt': typeof MainLabsJwtRoute
  '/_main/labs/lexicon-validator': typeof MainLabsLexiconValidatorRoute
  '/_main/labs/life': typeof MainLabsLifeRoute
  '/_main/labs/lightning': typeof MainLabsLightningRoute
  '/_main/labs/list-cleaner': typeof MainLabsListCleanerRoute
  '/_main/labs/matrix': typeof MainLabsMatrixRoute
  '/_main/labs/mp': typeof MainLabsMpRoute
  '/_main/labs/og-preview': typeof MainLabsOgPreviewRoute
  '/_main/labs/palette': typeof MainLabsPaletteRoute
  '/_main/labs/password': typeof MainLabsPasswordRoute
  '/_main/labs/pdf-uploader': typeof MainLabsPdfUploaderRoute
  '/_main/labs/pds-health': typeof MainLabsPdsHealthRoute
  '/_main/labs/periodic': typeof MainLabsPeriodicRoute
  '/_main/labs/png-chunks': typeof MainLabsPngChunksRoute
  '/_main/labs/regex': typeof MainLabsRegexRoute
  '/_main/labs/schema': typeof MainLabsSchemaRoute
  '/_main/labs/screenshot-maker': typeof MainLabsScreenshotMakerRoute
  '/_main/labs/snake': typeof MainLabsSnakeRoute
  '/_main/labs/spectrogram': typeof MainLabsSpectrogramRoute
  '/_main/labs/subnet': typeof MainLabsSubnetRoute
  '/_main/labs/terminal': typeof MainLabsTerminalRoute
  '/_main/labs/tfl-air': typeof MainLabsTflAirRoute
  '/_main/labs/tfl-arrivals': typeof MainLabsTflArrivalsRoute
  '/_main/labs/tfl-cycles': typeof MainLabsTflCyclesRoute
  '/_main/labs/tfl-roads': typeof MainLabsTflRoadsRoute
  '/_main/labs/tfl-status': typeof MainLabsTflStatusRoute
  '/_main/labs/tfl-tube-map': typeof MainLabsTflTubeMapRoute
  '/_main/labs/thread-tree': typeof MainLabsThreadTreeRoute
  '/_main/labs/tid': typeof MainLabsTidRoute
  '/_main/labs/timestamp': typeof MainLabsTimestampRoute
  '/_main/labs/typing': typeof MainLabsTypingRoute
  '/_main/labs/ua': typeof MainLabsUaRoute
  '/_main/labs/unicode': typeof MainLabsUnicodeRoute
  '/_main/labs/units': typeof MainLabsUnitsRoute
  '/_main/labs/verse-reveal': typeof MainLabsVerseRevealRoute
  '/_main/labs/whois': typeof MainLabsWhoisRoute
  '/_main/labs/wordle': typeof MainLabsWordleRoute
  '/_main/projects/$name': typeof MainProjectsNameRoute
  '/_main/watching/$rkey': typeof MainWatchingRkeyRoute
  '/_main/blog/': typeof MainBlogIndexRoute
  '/_main/games/': typeof MainGamesIndexRoute
  '/_main/labs/': typeof MainLabsIndexRoute
  '/_main/projects/': typeof MainProjectsIndexRoute
  '/_main/watching/': typeof MainWatchingIndexRoute
  '/_main/labs/at-uri/$': typeof MainLabsAtUriSplatRoute
  '/_main/labs/car-explorer/$': typeof MainLabsCarExplorerSplatRoute
  '/_main/labs/css-battles/$date': typeof MainLabsCssBattlesDateRoute
  '/_main/labs/feed/$': typeof MainLabsFeedSplatRoute
  '/_main/labs/lexicon/$nsid': typeof MainLabsLexiconNsidRoute
  '/_main/labs/plc-log/$': typeof MainLabsPlcLogSplatRoute
  '/_main/pokedex/$rkey/$pokeId': typeof MainPokedexRkeyPokeIdRoute
  '/_main/labs/at-uri/': typeof MainLabsAtUriIndexRoute
  '/_main/labs/car-explorer/': typeof MainLabsCarExplorerIndexRoute
  '/_main/labs/css-battles/': typeof MainLabsCssBattlesIndexRoute
  '/_main/labs/feed/': typeof MainLabsFeedIndexRoute
  '/_main/labs/lexicon/': typeof MainLabsLexiconIndexRoute
  '/_main/labs/plc-log/': typeof MainLabsPlcLogIndexRoute
  '/_main/labs/year-in-review/': typeof MainLabsYearInReviewIndexRoute
  '/_main/labs/year-in-review/$handle/$year': typeof MainLabsYearInReviewHandleYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/ai'
    | '/bookmarks'
    | '/design-system'
    | '/gallery'
    | '/globe'
    | '/guestbook'
    | '/health'
    | '/homelab'
    | '/library'
    | '/music'
    | '/uses'
    | '/oauth/callback'
    | '/og/$'
    | '/blog/$rkey'
    | '/games/$rkey'
    | '/labs/ascii'
    | '/labs/browser'
    | '/labs/bsky-composer'
    | '/labs/case'
    | '/labs/certs'
    | '/labs/colour'
    | '/labs/crime'
    | '/labs/cron'
    | '/labs/crypto'
    | '/labs/csv'
    | '/labs/curl'
    | '/labs/did-log'
    | '/labs/diff'
    | '/labs/dist'
    | '/labs/dns'
    | '/labs/encode'
    | '/labs/exif'
    | '/labs/fingerprint'
    | '/labs/firehose-stats'
    | '/labs/handle-sniper'
    | '/labs/hash'
    | '/labs/hex-dump'
    | '/labs/http-headers'
    | '/labs/http-status'
    | '/labs/hygiene'
    | '/labs/ids'
    | '/labs/infinite-canvas'
    | '/labs/iss'
    | '/labs/jetstream'
    | '/labs/json'
    | '/labs/jwt'
    | '/labs/lexicon-validator'
    | '/labs/life'
    | '/labs/lightning'
    | '/labs/list-cleaner'
    | '/labs/matrix'
    | '/labs/mp'
    | '/labs/og-preview'
    | '/labs/palette'
    | '/labs/password'
    | '/labs/pdf-uploader'
    | '/labs/pds-health'
    | '/labs/periodic'
    | '/labs/png-chunks'
    | '/labs/regex'
    | '/labs/schema'
    | '/labs/screenshot-maker'
    | '/labs/snake'
    | '/labs/spectrogram'
    | '/labs/subnet'
    | '/labs/terminal'
    | '/labs/tfl-air'
    | '/labs/tfl-arrivals'
    | '/labs/tfl-cycles'
    | '/labs/tfl-roads'
    | '/labs/tfl-status'
    | '/labs/tfl-tube-map'
    | '/labs/thread-tree'
    | '/labs/tid'
    | '/labs/timestamp'
    | '/labs/typing'
    | '/labs/ua'
    | '/labs/unicode'
    | '/labs/units'
    | '/labs/verse-reveal'
    | '/labs/whois'
    | '/labs/wordle'
    | '/projects/$name'
    | '/watching/$rkey'
    | '/blog/'
    | '/games/'
    | '/labs/'
    | '/projects/'
    | '/watching/'
    | '/labs/at-uri/$'
    | '/labs/car-explorer/$'
    | '/labs/css-battles/$date'
    | '/labs/feed/$'
    | '/labs/lexicon/$nsid'
    | '/labs/plc-log/$'
    | '/pokedex/$rkey/$pokeId'
    | '/labs/at-uri/'
    | '/labs/car-explorer/'
    | '/labs/css-battles/'
    | '/labs/feed/'
    | '/labs/lexicon/'
    | '/labs/plc-log/'
    | '/labs/year-in-review/'
    | '/labs/year-in-review/$handle/$year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/ai'
    | '/bookmarks'
    | '/design-system'
    | '/gallery'
    | '/globe'
    | '/guestbook'
    | '/health'
    | '/homelab'
    | '/library'
    | '/music'
    | '/uses'
    | '/oauth/callback'
    | '/og/$'
    | '/'
    | '/blog/$rkey'
    | '/games/$rkey'
    | '/labs/ascii'
    | '/labs/browser'
    | '/labs/bsky-composer'
    | '/labs/case'
    | '/labs/certs'
    | '/labs/colour'
    | '/labs/crime'
    | '/labs/cron'
    | '/labs/crypto'
    | '/labs/csv'
    | '/labs/curl'
    | '/labs/did-log'
    | '/labs/diff'
    | '/labs/dist'
    | '/labs/dns'
    | '/labs/encode'
    | '/labs/exif'
    | '/labs/fingerprint'
    | '/labs/firehose-stats'
    | '/labs/handle-sniper'
    | '/labs/hash'
    | '/labs/hex-dump'
    | '/labs/http-headers'
    | '/labs/http-status'
    | '/labs/hygiene'
    | '/labs/ids'
    | '/labs/infinite-canvas'
    | '/labs/iss'
    | '/labs/jetstream'
    | '/labs/json'
    | '/labs/jwt'
    | '/labs/lexicon-validator'
    | '/labs/life'
    | '/labs/lightning'
    | '/labs/list-cleaner'
    | '/labs/matrix'
    | '/labs/mp'
    | '/labs/og-preview'
    | '/labs/palette'
    | '/labs/password'
    | '/labs/pdf-uploader'
    | '/labs/pds-health'
    | '/labs/periodic'
    | '/labs/png-chunks'
    | '/labs/regex'
    | '/labs/schema'
    | '/labs/screenshot-maker'
    | '/labs/snake'
    | '/labs/spectrogram'
    | '/labs/subnet'
    | '/labs/terminal'
    | '/labs/tfl-air'
    | '/labs/tfl-arrivals'
    | '/labs/tfl-cycles'
    | '/labs/tfl-roads'
    | '/labs/tfl-status'
    | '/labs/tfl-tube-map'
    | '/labs/thread-tree'
    | '/labs/tid'
    | '/labs/timestamp'
    | '/labs/typing'
    | '/labs/ua'
    | '/labs/unicode'
    | '/labs/units'
    | '/labs/verse-reveal'
    | '/labs/whois'
    | '/labs/wordle'
    | '/projects/$name'
    | '/watching/$rkey'
    | '/blog'
    | '/games'
    | '/labs'
    | '/projects'
    | '/watching'
    | '/labs/at-uri/$'
    | '/labs/car-explorer/$'
    | '/labs/css-battles/$date'
    | '/labs/feed/$'
    | '/labs/lexicon/$nsid'
    | '/labs/plc-log/$'
    | '/pokedex/$rkey/$pokeId'
    | '/labs/at-uri'
    | '/labs/car-explorer'
    | '/labs/css-battles'
    | '/labs/feed'
    | '/labs/lexicon'
    | '/labs/plc-log'
    | '/labs/year-in-review'
    | '/labs/year-in-review/$handle/$year'
  id:
    | '__root__'
    | '/_main'
    | '/sitemap.xml'
    | '/_main/ai'
    | '/_main/bookmarks'
    | '/_main/design-system'
    | '/_main/gallery'
    | '/_main/globe'
    | '/_main/guestbook'
    | '/_main/health'
    | '/_main/homelab'
    | '/_main/library'
    | '/_main/music'
    | '/_main/uses'
    | '/oauth/callback'
    | '/og/$'
    | '/_main/'
    | '/_main/blog/$rkey'
    | '/_main/games/$rkey'
    | '/_main/labs/ascii'
    | '/_main/labs/browser'
    | '/_main/labs/bsky-composer'
    | '/_main/labs/case'
    | '/_main/labs/certs'
    | '/_main/labs/colour'
    | '/_main/labs/crime'
    | '/_main/labs/cron'
    | '/_main/labs/crypto'
    | '/_main/labs/csv'
    | '/_main/labs/curl'
    | '/_main/labs/did-log'
    | '/_main/labs/diff'
    | '/_main/labs/dist'
    | '/_main/labs/dns'
    | '/_main/labs/encode'
    | '/_main/labs/exif'
    | '/_main/labs/fingerprint'
    | '/_main/labs/firehose-stats'
    | '/_main/labs/handle-sniper'
    | '/_main/labs/hash'
    | '/_main/labs/hex-dump'
    | '/_main/labs/http-headers'
    | '/_main/labs/http-status'
    | '/_main/labs/hygiene'
    | '/_main/labs/ids'
    | '/_main/labs/infinite-canvas'
    | '/_main/labs/iss'
    | '/_main/labs/jetstream'
    | '/_main/labs/json'
    | '/_main/labs/jwt'
    | '/_main/labs/lexicon-validator'
    | '/_main/labs/life'
    | '/_main/labs/lightning'
    | '/_main/labs/list-cleaner'
    | '/_main/labs/matrix'
    | '/_main/labs/mp'
    | '/_main/labs/og-preview'
    | '/_main/labs/palette'
    | '/_main/labs/password'
    | '/_main/labs/pdf-uploader'
    | '/_main/labs/pds-health'
    | '/_main/labs/periodic'
    | '/_main/labs/png-chunks'
    | '/_main/labs/regex'
    | '/_main/labs/schema'
    | '/_main/labs/screenshot-maker'
    | '/_main/labs/snake'
    | '/_main/labs/spectrogram'
    | '/_main/labs/subnet'
    | '/_main/labs/terminal'
    | '/_main/labs/tfl-air'
    | '/_main/labs/tfl-arrivals'
    | '/_main/labs/tfl-cycles'
    | '/_main/labs/tfl-roads'
    | '/_main/labs/tfl-status'
    | '/_main/labs/tfl-tube-map'
    | '/_main/labs/thread-tree'
    | '/_main/labs/tid'
    | '/_main/labs/timestamp'
    | '/_main/labs/typing'
    | '/_main/labs/ua'
    | '/_main/labs/unicode'
    | '/_main/labs/units'
    | '/_main/labs/verse-reveal'
    | '/_main/labs/whois'
    | '/_main/labs/wordle'
    | '/_main/projects/$name'
    | '/_main/watching/$rkey'
    | '/_main/blog/'
    | '/_main/games/'
    | '/_main/labs/'
    | '/_main/projects/'
    | '/_main/watching/'
    | '/_main/labs/at-uri/$'
    | '/_main/labs/car-explorer/$'
    | '/_main/labs/css-battles/$date'
    | '/_main/labs/feed/$'
    | '/_main/labs/lexicon/$nsid'
    | '/_main/labs/plc-log/$'
    | '/_main/pokedex/$rkey/$pokeId'
    | '/_main/labs/at-uri/'
    | '/_main/labs/car-explorer/'
    | '/_main/labs/css-battles/'
    | '/_main/labs/feed/'
    | '/_main/labs/lexicon/'
    | '/_main/labs/plc-log/'
    | '/_main/labs/year-in-review/'
    | '/_main/labs/year-in-review/$handle/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OgSplatRoute: typeof OgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/og/$': {
      id: '/og/$'
      path: '/og/$'
      fullPath: '/og/$'
      preLoaderRoute: typeof OgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/uses': {
      id: '/_main/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof MainUsesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/music': {
      id: '/_main/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MainMusicRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/library': {
      id: '/_main/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof MainLibraryRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/homelab': {
      id: '/_main/homelab'
      path: '/homelab'
      fullPath: '/homelab'
      preLoaderRoute: typeof MainHomelabRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/health': {
      id: '/_main/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof MainHealthRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/guestbook': {
      id: '/_main/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof MainGuestbookRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/globe': {
      id: '/_main/globe'
      path: '/globe'
      fullPath: '/globe'
      preLoaderRoute: typeof MainGlobeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/gallery': {
      id: '/_main/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof MainGalleryRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/design-system': {
      id: '/_main/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof MainDesignSystemRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/bookmarks': {
      id: '/_main/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof MainBookmarksRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ai': {
      id: '/_main/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof MainAiRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/watching/': {
      id: '/_main/watching/'
      path: '/watching'
      fullPath: '/watching/'
      preLoaderRoute: typeof MainWatchingIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/': {
      id: '/_main/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof MainProjectsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/': {
      id: '/_main/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof MainLabsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/games/': {
      id: '/_main/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof MainGamesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/': {
      id: '/_main/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof MainBlogIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/watching/$rkey': {
      id: '/_main/watching/$rkey'
      path: '/watching/$rkey'
      fullPath: '/watching/$rkey'
      preLoaderRoute: typeof MainWatchingRkeyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/$name': {
      id: '/_main/projects/$name'
      path: '/projects/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof MainProjectsNameRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/wordle': {
      id: '/_main/labs/wordle'
      path: '/labs/wordle'
      fullPath: '/labs/wordle'
      preLoaderRoute: typeof MainLabsWordleRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/whois': {
      id: '/_main/labs/whois'
      path: '/labs/whois'
      fullPath: '/labs/whois'
      preLoaderRoute: typeof MainLabsWhoisRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/verse-reveal': {
      id: '/_main/labs/verse-reveal'
      path: '/labs/verse-reveal'
      fullPath: '/labs/verse-reveal'
      preLoaderRoute: typeof MainLabsVerseRevealRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/units': {
      id: '/_main/labs/units'
      path: '/labs/units'
      fullPath: '/labs/units'
      preLoaderRoute: typeof MainLabsUnitsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/unicode': {
      id: '/_main/labs/unicode'
      path: '/labs/unicode'
      fullPath: '/labs/unicode'
      preLoaderRoute: typeof MainLabsUnicodeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/ua': {
      id: '/_main/labs/ua'
      path: '/labs/ua'
      fullPath: '/labs/ua'
      preLoaderRoute: typeof MainLabsUaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/typing': {
      id: '/_main/labs/typing'
      path: '/labs/typing'
      fullPath: '/labs/typing'
      preLoaderRoute: typeof MainLabsTypingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/timestamp': {
      id: '/_main/labs/timestamp'
      path: '/labs/timestamp'
      fullPath: '/labs/timestamp'
      preLoaderRoute: typeof MainLabsTimestampRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/tid': {
      id: '/_main/labs/tid'
      path: '/labs/tid'
      fullPath: '/labs/tid'
      preLoaderRoute: typeof MainLabsTidRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/thread-tree': {
      id: '/_main/labs/thread-tree'
      path: '/labs/thread-tree'
      fullPath: '/labs/thread-tree'
      preLoaderRoute: typeof MainLabsThreadTreeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/tfl-tube-map': {
      id: '/_main/labs/tfl-tube-map'
      path: '/labs/tfl-tube-map'
      fullPath: '/labs/tfl-tube-map'
      preLoaderRoute: typeof MainLabsTflTubeMapRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/tfl-status': {
      id: '/_main/labs/tfl-status'
      path: '/labs/tfl-status'
      fullPath: '/labs/tfl-status'
      preLoaderRoute: typeof MainLabsTflStatusRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/tfl-roads': {
      id: '/_main/labs/tfl-roads'
      path: '/labs/tfl-roads'
      fullPath: '/labs/tfl-roads'
      preLoaderRoute: typeof MainLabsTflRoadsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/tfl-cycles': {
      id: '/_main/labs/tfl-cycles'
      path: '/labs/tfl-cycles'
      fullPath: '/labs/tfl-cycles'
      preLoaderRoute: typeof MainLabsTflCyclesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/tfl-arrivals': {
      id: '/_main/labs/tfl-arrivals'
      path: '/labs/tfl-arrivals'
      fullPath: '/labs/tfl-arrivals'
      preLoaderRoute: typeof MainLabsTflArrivalsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/tfl-air': {
      id: '/_main/labs/tfl-air'
      path: '/labs/tfl-air'
      fullPath: '/labs/tfl-air'
      preLoaderRoute: typeof MainLabsTflAirRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/terminal': {
      id: '/_main/labs/terminal'
      path: '/labs/terminal'
      fullPath: '/labs/terminal'
      preLoaderRoute: typeof MainLabsTerminalRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/subnet': {
      id: '/_main/labs/subnet'
      path: '/labs/subnet'
      fullPath: '/labs/subnet'
      preLoaderRoute: typeof MainLabsSubnetRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/spectrogram': {
      id: '/_main/labs/spectrogram'
      path: '/labs/spectrogram'
      fullPath: '/labs/spectrogram'
      preLoaderRoute: typeof MainLabsSpectrogramRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/snake': {
      id: '/_main/labs/snake'
      path: '/labs/snake'
      fullPath: '/labs/snake'
      preLoaderRoute: typeof MainLabsSnakeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/screenshot-maker': {
      id: '/_main/labs/screenshot-maker'
      path: '/labs/screenshot-maker'
      fullPath: '/labs/screenshot-maker'
      preLoaderRoute: typeof MainLabsScreenshotMakerRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/schema': {
      id: '/_main/labs/schema'
      path: '/labs/schema'
      fullPath: '/labs/schema'
      preLoaderRoute: typeof MainLabsSchemaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/regex': {
      id: '/_main/labs/regex'
      path: '/labs/regex'
      fullPath: '/labs/regex'
      preLoaderRoute: typeof MainLabsRegexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/png-chunks': {
      id: '/_main/labs/png-chunks'
      path: '/labs/png-chunks'
      fullPath: '/labs/png-chunks'
      preLoaderRoute: typeof MainLabsPngChunksRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/periodic': {
      id: '/_main/labs/periodic'
      path: '/labs/periodic'
      fullPath: '/labs/periodic'
      preLoaderRoute: typeof MainLabsPeriodicRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/pds-health': {
      id: '/_main/labs/pds-health'
      path: '/labs/pds-health'
      fullPath: '/labs/pds-health'
      preLoaderRoute: typeof MainLabsPdsHealthRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/pdf-uploader': {
      id: '/_main/labs/pdf-uploader'
      path: '/labs/pdf-uploader'
      fullPath: '/labs/pdf-uploader'
      preLoaderRoute: typeof MainLabsPdfUploaderRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/password': {
      id: '/_main/labs/password'
      path: '/labs/password'
      fullPath: '/labs/password'
      preLoaderRoute: typeof MainLabsPasswordRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/palette': {
      id: '/_main/labs/palette'
      path: '/labs/palette'
      fullPath: '/labs/palette'
      preLoaderRoute: typeof MainLabsPaletteRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/og-preview': {
      id: '/_main/labs/og-preview'
      path: '/labs/og-preview'
      fullPath: '/labs/og-preview'
      preLoaderRoute: typeof MainLabsOgPreviewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/mp': {
      id: '/_main/labs/mp'
      path: '/labs/mp'
      fullPath: '/labs/mp'
      preLoaderRoute: typeof MainLabsMpRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/matrix': {
      id: '/_main/labs/matrix'
      path: '/labs/matrix'
      fullPath: '/labs/matrix'
      preLoaderRoute: typeof MainLabsMatrixRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/list-cleaner': {
      id: '/_main/labs/list-cleaner'
      path: '/labs/list-cleaner'
      fullPath: '/labs/list-cleaner'
      preLoaderRoute: typeof MainLabsListCleanerRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/lightning': {
      id: '/_main/labs/lightning'
      path: '/labs/lightning'
      fullPath: '/labs/lightning'
      preLoaderRoute: typeof MainLabsLightningRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/life': {
      id: '/_main/labs/life'
      path: '/labs/life'
      fullPath: '/labs/life'
      preLoaderRoute: typeof MainLabsLifeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/lexicon-validator': {
      id: '/_main/labs/lexicon-validator'
      path: '/labs/lexicon-validator'
      fullPath: '/labs/lexicon-validator'
      preLoaderRoute: typeof MainLabsLexiconValidatorRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/jwt': {
      id: '/_main/labs/jwt'
      path: '/labs/jwt'
      fullPath: '/labs/jwt'
      preLoaderRoute: typeof MainLabsJwtRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/json': {
      id: '/_main/labs/json'
      path: '/labs/json'
      fullPath: '/labs/json'
      preLoaderRoute: typeof MainLabsJsonRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/jetstream': {
      id: '/_main/labs/jetstream'
      path: '/labs/jetstream'
      fullPath: '/labs/jetstream'
      preLoaderRoute: typeof MainLabsJetstreamRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/iss': {
      id: '/_main/labs/iss'
      path: '/labs/iss'
      fullPath: '/labs/iss'
      preLoaderRoute: typeof MainLabsIssRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/infinite-canvas': {
      id: '/_main/labs/infinite-canvas'
      path: '/labs/infinite-canvas'
      fullPath: '/labs/infinite-canvas'
      preLoaderRoute: typeof MainLabsInfiniteCanvasRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/ids': {
      id: '/_main/labs/ids'
      path: '/labs/ids'
      fullPath: '/labs/ids'
      preLoaderRoute: typeof MainLabsIdsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/hygiene': {
      id: '/_main/labs/hygiene'
      path: '/labs/hygiene'
      fullPath: '/labs/hygiene'
      preLoaderRoute: typeof MainLabsHygieneRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/http-status': {
      id: '/_main/labs/http-status'
      path: '/labs/http-status'
      fullPath: '/labs/http-status'
      preLoaderRoute: typeof MainLabsHttpStatusRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/http-headers': {
      id: '/_main/labs/http-headers'
      path: '/labs/http-headers'
      fullPath: '/labs/http-headers'
      preLoaderRoute: typeof MainLabsHttpHeadersRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/hex-dump': {
      id: '/_main/labs/hex-dump'
      path: '/labs/hex-dump'
      fullPath: '/labs/hex-dump'
      preLoaderRoute: typeof MainLabsHexDumpRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/hash': {
      id: '/_main/labs/hash'
      path: '/labs/hash'
      fullPath: '/labs/hash'
      preLoaderRoute: typeof MainLabsHashRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/handle-sniper': {
      id: '/_main/labs/handle-sniper'
      path: '/labs/handle-sniper'
      fullPath: '/labs/handle-sniper'
      preLoaderRoute: typeof MainLabsHandleSniperRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/firehose-stats': {
      id: '/_main/labs/firehose-stats'
      path: '/labs/firehose-stats'
      fullPath: '/labs/firehose-stats'
      preLoaderRoute: typeof MainLabsFirehoseStatsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/fingerprint': {
      id: '/_main/labs/fingerprint'
      path: '/labs/fingerprint'
      fullPath: '/labs/fingerprint'
      preLoaderRoute: typeof MainLabsFingerprintRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/exif': {
      id: '/_main/labs/exif'
      path: '/labs/exif'
      fullPath: '/labs/exif'
      preLoaderRoute: typeof MainLabsExifRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/encode': {
      id: '/_main/labs/encode'
      path: '/labs/encode'
      fullPath: '/labs/encode'
      preLoaderRoute: typeof MainLabsEncodeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/dns': {
      id: '/_main/labs/dns'
      path: '/labs/dns'
      fullPath: '/labs/dns'
      preLoaderRoute: typeof MainLabsDnsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/dist': {
      id: '/_main/labs/dist'
      path: '/labs/dist'
      fullPath: '/labs/dist'
      preLoaderRoute: typeof MainLabsDistRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/diff': {
      id: '/_main/labs/diff'
      path: '/labs/diff'
      fullPath: '/labs/diff'
      preLoaderRoute: typeof MainLabsDiffRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/did-log': {
      id: '/_main/labs/did-log'
      path: '/labs/did-log'
      fullPath: '/labs/did-log'
      preLoaderRoute: typeof MainLabsDidLogRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/curl': {
      id: '/_main/labs/curl'
      path: '/labs/curl'
      fullPath: '/labs/curl'
      preLoaderRoute: typeof MainLabsCurlRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/csv': {
      id: '/_main/labs/csv'
      path: '/labs/csv'
      fullPath: '/labs/csv'
      preLoaderRoute: typeof MainLabsCsvRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/crypto': {
      id: '/_main/labs/crypto'
      path: '/labs/crypto'
      fullPath: '/labs/crypto'
      preLoaderRoute: typeof MainLabsCryptoRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/cron': {
      id: '/_main/labs/cron'
      path: '/labs/cron'
      fullPath: '/labs/cron'
      preLoaderRoute: typeof MainLabsCronRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/crime': {
      id: '/_main/labs/crime'
      path: '/labs/crime'
      fullPath: '/labs/crime'
      preLoaderRoute: typeof MainLabsCrimeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/colour': {
      id: '/_main/labs/colour'
      path: '/labs/colour'
      fullPath: '/labs/colour'
      preLoaderRoute: typeof MainLabsColourRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/certs': {
      id: '/_main/labs/certs'
      path: '/labs/certs'
      fullPath: '/labs/certs'
      preLoaderRoute: typeof MainLabsCertsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/case': {
      id: '/_main/labs/case'
      path: '/labs/case'
      fullPath: '/labs/case'
      preLoaderRoute: typeof MainLabsCaseRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/bsky-composer': {
      id: '/_main/labs/bsky-composer'
      path: '/labs/bsky-composer'
      fullPath: '/labs/bsky-composer'
      preLoaderRoute: typeof MainLabsBskyComposerRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/browser': {
      id: '/_main/labs/browser'
      path: '/labs/browser'
      fullPath: '/labs/browser'
      preLoaderRoute: typeof MainLabsBrowserRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/ascii': {
      id: '/_main/labs/ascii'
      path: '/labs/ascii'
      fullPath: '/labs/ascii'
      preLoaderRoute: typeof MainLabsAsciiRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/games/$rkey': {
      id: '/_main/games/$rkey'
      path: '/games/$rkey'
      fullPath: '/games/$rkey'
      preLoaderRoute: typeof MainGamesRkeyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/$rkey': {
      id: '/_main/blog/$rkey'
      path: '/blog/$rkey'
      fullPath: '/blog/$rkey'
      preLoaderRoute: typeof MainBlogRkeyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/year-in-review/': {
      id: '/_main/labs/year-in-review/'
      path: '/labs/year-in-review'
      fullPath: '/labs/year-in-review/'
      preLoaderRoute: typeof MainLabsYearInReviewIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/plc-log/': {
      id: '/_main/labs/plc-log/'
      path: '/labs/plc-log'
      fullPath: '/labs/plc-log/'
      preLoaderRoute: typeof MainLabsPlcLogIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/lexicon/': {
      id: '/_main/labs/lexicon/'
      path: '/labs/lexicon'
      fullPath: '/labs/lexicon/'
      preLoaderRoute: typeof MainLabsLexiconIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/feed/': {
      id: '/_main/labs/feed/'
      path: '/labs/feed'
      fullPath: '/labs/feed/'
      preLoaderRoute: typeof MainLabsFeedIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/css-battles/': {
      id: '/_main/labs/css-battles/'
      path: '/labs/css-battles'
      fullPath: '/labs/css-battles/'
      preLoaderRoute: typeof MainLabsCssBattlesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/car-explorer/': {
      id: '/_main/labs/car-explorer/'
      path: '/labs/car-explorer'
      fullPath: '/labs/car-explorer/'
      preLoaderRoute: typeof MainLabsCarExplorerIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/at-uri/': {
      id: '/_main/labs/at-uri/'
      path: '/labs/at-uri'
      fullPath: '/labs/at-uri/'
      preLoaderRoute: typeof MainLabsAtUriIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/pokedex/$rkey/$pokeId': {
      id: '/_main/pokedex/$rkey/$pokeId'
      path: '/pokedex/$rkey/$pokeId'
      fullPath: '/pokedex/$rkey/$pokeId'
      preLoaderRoute: typeof MainPokedexRkeyPokeIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/plc-log/$': {
      id: '/_main/labs/plc-log/$'
      path: '/labs/plc-log/$'
      fullPath: '/labs/plc-log/$'
      preLoaderRoute: typeof MainLabsPlcLogSplatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/lexicon/$nsid': {
      id: '/_main/labs/lexicon/$nsid'
      path: '/labs/lexicon/$nsid'
      fullPath: '/labs/lexicon/$nsid'
      preLoaderRoute: typeof MainLabsLexiconNsidRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/feed/$': {
      id: '/_main/labs/feed/$'
      path: '/labs/feed/$'
      fullPath: '/labs/feed/$'
      preLoaderRoute: typeof MainLabsFeedSplatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/css-battles/$date': {
      id: '/_main/labs/css-battles/$date'
      path: '/labs/css-battles/$date'
      fullPath: '/labs/css-battles/$date'
      preLoaderRoute: typeof MainLabsCssBattlesDateRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/car-explorer/$': {
      id: '/_main/labs/car-explorer/$'
      path: '/labs/car-explorer/$'
      fullPath: '/labs/car-explorer/$'
      preLoaderRoute: typeof MainLabsCarExplorerSplatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/at-uri/$': {
      id: '/_main/labs/at-uri/$'
      path: '/labs/at-uri/$'
      fullPath: '/labs/at-uri/$'
      preLoaderRoute: typeof MainLabsAtUriSplatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/year-in-review/$handle/$year': {
      id: '/_main/labs/year-in-review/$handle/$year'
      path: '/labs/year-in-review/$handle/$year'
      fullPath: '/labs/year-in-review/$handle/$year'
      preLoaderRoute: typeof MainLabsYearInReviewHandleYearRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainAiRoute: typeof MainAiRoute
  MainBookmarksRoute: typeof MainBookmarksRoute
  MainDesignSystemRoute: typeof MainDesignSystemRoute
  MainGalleryRoute: typeof MainGalleryRoute
  MainGlobeRoute: typeof MainGlobeRoute
  MainGuestbookRoute: typeof MainGuestbookRoute
  MainHealthRoute: typeof MainHealthRoute
  MainHomelabRoute: typeof MainHomelabRoute
  MainLibraryRoute: typeof MainLibraryRoute
  MainMusicRoute: typeof MainMusicRoute
  MainUsesRoute: typeof MainUsesRoute
  MainIndexRoute: typeof MainIndexRoute
  MainBlogRkeyRoute: typeof MainBlogRkeyRoute
  MainGamesRkeyRoute: typeof MainGamesRkeyRoute
  MainLabsAsciiRoute: typeof MainLabsAsciiRoute
  MainLabsBrowserRoute: typeof MainLabsBrowserRoute
  MainLabsBskyComposerRoute: typeof MainLabsBskyComposerRoute
  MainLabsCaseRoute: typeof MainLabsCaseRoute
  MainLabsCertsRoute: typeof MainLabsCertsRoute
  MainLabsColourRoute: typeof MainLabsColourRoute
  MainLabsCrimeRoute: typeof MainLabsCrimeRoute
  MainLabsCronRoute: typeof MainLabsCronRoute
  MainLabsCryptoRoute: typeof MainLabsCryptoRoute
  MainLabsCsvRoute: typeof MainLabsCsvRoute
  MainLabsCurlRoute: typeof MainLabsCurlRoute
  MainLabsDidLogRoute: typeof MainLabsDidLogRoute
  MainLabsDiffRoute: typeof MainLabsDiffRoute
  MainLabsDistRoute: typeof MainLabsDistRoute
  MainLabsDnsRoute: typeof MainLabsDnsRoute
  MainLabsEncodeRoute: typeof MainLabsEncodeRoute
  MainLabsExifRoute: typeof MainLabsExifRoute
  MainLabsFingerprintRoute: typeof MainLabsFingerprintRoute
  MainLabsFirehoseStatsRoute: typeof MainLabsFirehoseStatsRoute
  MainLabsHandleSniperRoute: typeof MainLabsHandleSniperRoute
  MainLabsHashRoute: typeof MainLabsHashRoute
  MainLabsHexDumpRoute: typeof MainLabsHexDumpRoute
  MainLabsHttpHeadersRoute: typeof MainLabsHttpHeadersRoute
  MainLabsHttpStatusRoute: typeof MainLabsHttpStatusRoute
  MainLabsHygieneRoute: typeof MainLabsHygieneRoute
  MainLabsIdsRoute: typeof MainLabsIdsRoute
  MainLabsInfiniteCanvasRoute: typeof MainLabsInfiniteCanvasRoute
  MainLabsIssRoute: typeof MainLabsIssRoute
  MainLabsJetstreamRoute: typeof MainLabsJetstreamRoute
  MainLabsJsonRoute: typeof MainLabsJsonRoute
  MainLabsJwtRoute: typeof MainLabsJwtRoute
  MainLabsLexiconValidatorRoute: typeof MainLabsLexiconValidatorRoute
  MainLabsLifeRoute: typeof MainLabsLifeRoute
  MainLabsLightningRoute: typeof MainLabsLightningRoute
  MainLabsListCleanerRoute: typeof MainLabsListCleanerRoute
  MainLabsMatrixRoute: typeof MainLabsMatrixRoute
  MainLabsMpRoute: typeof MainLabsMpRoute
  MainLabsOgPreviewRoute: typeof MainLabsOgPreviewRoute
  MainLabsPaletteRoute: typeof MainLabsPaletteRoute
  MainLabsPasswordRoute: typeof MainLabsPasswordRoute
  MainLabsPdfUploaderRoute: typeof MainLabsPdfUploaderRoute
  MainLabsPdsHealthRoute: typeof MainLabsPdsHealthRoute
  MainLabsPeriodicRoute: typeof MainLabsPeriodicRoute
  MainLabsPngChunksRoute: typeof MainLabsPngChunksRoute
  MainLabsRegexRoute: typeof MainLabsRegexRoute
  MainLabsSchemaRoute: typeof MainLabsSchemaRoute
  MainLabsScreenshotMakerRoute: typeof MainLabsScreenshotMakerRoute
  MainLabsSnakeRoute: typeof MainLabsSnakeRoute
  MainLabsSpectrogramRoute: typeof MainLabsSpectrogramRoute
  MainLabsSubnetRoute: typeof MainLabsSubnetRoute
  MainLabsTerminalRoute: typeof MainLabsTerminalRoute
  MainLabsTflAirRoute: typeof MainLabsTflAirRoute
  MainLabsTflArrivalsRoute: typeof MainLabsTflArrivalsRoute
  MainLabsTflCyclesRoute: typeof MainLabsTflCyclesRoute
  MainLabsTflRoadsRoute: typeof MainLabsTflRoadsRoute
  MainLabsTflStatusRoute: typeof MainLabsTflStatusRoute
  MainLabsTflTubeMapRoute: typeof MainLabsTflTubeMapRoute
  MainLabsThreadTreeRoute: typeof MainLabsThreadTreeRoute
  MainLabsTidRoute: typeof MainLabsTidRoute
  MainLabsTimestampRoute: typeof MainLabsTimestampRoute
  MainLabsTypingRoute: typeof MainLabsTypingRoute
  MainLabsUaRoute: typeof MainLabsUaRoute
  MainLabsUnicodeRoute: typeof MainLabsUnicodeRoute
  MainLabsUnitsRoute: typeof MainLabsUnitsRoute
  MainLabsVerseRevealRoute: typeof MainLabsVerseRevealRoute
  MainLabsWhoisRoute: typeof MainLabsWhoisRoute
  MainLabsWordleRoute: typeof MainLabsWordleRoute
  MainProjectsNameRoute: typeof MainProjectsNameRoute
  MainWatchingRkeyRoute: typeof MainWatchingRkeyRoute
  MainBlogIndexRoute: typeof MainBlogIndexRoute
  MainGamesIndexRoute: typeof MainGamesIndexRoute
  MainLabsIndexRoute: typeof MainLabsIndexRoute
  MainProjectsIndexRoute: typeof MainProjectsIndexRoute
  MainWatchingIndexRoute: typeof MainWatchingIndexRoute
  MainLabsAtUriSplatRoute: typeof MainLabsAtUriSplatRoute
  MainLabsCarExplorerSplatRoute: typeof MainLabsCarExplorerSplatRoute
  MainLabsCssBattlesDateRoute: typeof MainLabsCssBattlesDateRoute
  MainLabsFeedSplatRoute: typeof MainLabsFeedSplatRoute
  MainLabsLexiconNsidRoute: typeof MainLabsLexiconNsidRoute
  MainLabsPlcLogSplatRoute: typeof MainLabsPlcLogSplatRoute
  MainPokedexRkeyPokeIdRoute: typeof MainPokedexRkeyPokeIdRoute
  MainLabsAtUriIndexRoute: typeof MainLabsAtUriIndexRoute
  MainLabsCarExplorerIndexRoute: typeof MainLabsCarExplorerIndexRoute
  MainLabsCssBattlesIndexRoute: typeof MainLabsCssBattlesIndexRoute
  MainLabsFeedIndexRoute: typeof MainLabsFeedIndexRoute
  MainLabsLexiconIndexRoute: typeof MainLabsLexiconIndexRoute
  MainLabsPlcLogIndexRoute: typeof MainLabsPlcLogIndexRoute
  MainLabsYearInReviewIndexRoute: typeof MainLabsYearInReviewIndexRoute
  MainLabsYearInReviewHandleYearRoute: typeof MainLabsYearInReviewHandleYearRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAiRoute: MainAiRoute,
  MainBookmarksRoute: MainBookmarksRoute,
  MainDesignSystemRoute: MainDesignSystemRoute,
  MainGalleryRoute: MainGalleryRoute,
  MainGlobeRoute: MainGlobeRoute,
  MainGuestbookRoute: MainGuestbookRoute,
  MainHealthRoute: MainHealthRoute,
  MainHomelabRoute: MainHomelabRoute,
  MainLibraryRoute: MainLibraryRoute,
  MainMusicRoute: MainMusicRoute,
  MainUsesRoute: MainUsesRoute,
  MainIndexRoute: MainIndexRoute,
  MainBlogRkeyRoute: MainBlogRkeyRoute,
  MainGamesRkeyRoute: MainGamesRkeyRoute,
  MainLabsAsciiRoute: MainLabsAsciiRoute,
  MainLabsBrowserRoute: MainLabsBrowserRoute,
  MainLabsBskyComposerRoute: MainLabsBskyComposerRoute,
  MainLabsCaseRoute: MainLabsCaseRoute,
  MainLabsCertsRoute: MainLabsCertsRoute,
  MainLabsColourRoute: MainLabsColourRoute,
  MainLabsCrimeRoute: MainLabsCrimeRoute,
  MainLabsCronRoute: MainLabsCronRoute,
  MainLabsCryptoRoute: MainLabsCryptoRoute,
  MainLabsCsvRoute: MainLabsCsvRoute,
  MainLabsCurlRoute: MainLabsCurlRoute,
  MainLabsDidLogRoute: MainLabsDidLogRoute,
  MainLabsDiffRoute: MainLabsDiffRoute,
  MainLabsDistRoute: MainLabsDistRoute,
  MainLabsDnsRoute: MainLabsDnsRoute,
  MainLabsEncodeRoute: MainLabsEncodeRoute,
  MainLabsExifRoute: MainLabsExifRoute,
  MainLabsFingerprintRoute: MainLabsFingerprintRoute,
  MainLabsFirehoseStatsRoute: MainLabsFirehoseStatsRoute,
  MainLabsHandleSniperRoute: MainLabsHandleSniperRoute,
  MainLabsHashRoute: MainLabsHashRoute,
  MainLabsHexDumpRoute: MainLabsHexDumpRoute,
  MainLabsHttpHeadersRoute: MainLabsHttpHeadersRoute,
  MainLabsHttpStatusRoute: MainLabsHttpStatusRoute,
  MainLabsHygieneRoute: MainLabsHygieneRoute,
  MainLabsIdsRoute: MainLabsIdsRoute,
  MainLabsInfiniteCanvasRoute: MainLabsInfiniteCanvasRoute,
  MainLabsIssRoute: MainLabsIssRoute,
  MainLabsJetstreamRoute: MainLabsJetstreamRoute,
  MainLabsJsonRoute: MainLabsJsonRoute,
  MainLabsJwtRoute: MainLabsJwtRoute,
  MainLabsLexiconValidatorRoute: MainLabsLexiconValidatorRoute,
  MainLabsLifeRoute: MainLabsLifeRoute,
  MainLabsLightningRoute: MainLabsLightningRoute,
  MainLabsListCleanerRoute: MainLabsListCleanerRoute,
  MainLabsMatrixRoute: MainLabsMatrixRoute,
  MainLabsMpRoute: MainLabsMpRoute,
  MainLabsOgPreviewRoute: MainLabsOgPreviewRoute,
  MainLabsPaletteRoute: MainLabsPaletteRoute,
  MainLabsPasswordRoute: MainLabsPasswordRoute,
  MainLabsPdfUploaderRoute: MainLabsPdfUploaderRoute,
  MainLabsPdsHealthRoute: MainLabsPdsHealthRoute,
  MainLabsPeriodicRoute: MainLabsPeriodicRoute,
  MainLabsPngChunksRoute: MainLabsPngChunksRoute,
  MainLabsRegexRoute: MainLabsRegexRoute,
  MainLabsSchemaRoute: MainLabsSchemaRoute,
  MainLabsScreenshotMakerRoute: MainLabsScreenshotMakerRoute,
  MainLabsSnakeRoute: MainLabsSnakeRoute,
  MainLabsSpectrogramRoute: MainLabsSpectrogramRoute,
  MainLabsSubnetRoute: MainLabsSubnetRoute,
  MainLabsTerminalRoute: MainLabsTerminalRoute,
  MainLabsTflAirRoute: MainLabsTflAirRoute,
  MainLabsTflArrivalsRoute: MainLabsTflArrivalsRoute,
  MainLabsTflCyclesRoute: MainLabsTflCyclesRoute,
  MainLabsTflRoadsRoute: MainLabsTflRoadsRoute,
  MainLabsTflStatusRoute: MainLabsTflStatusRoute,
  MainLabsTflTubeMapRoute: MainLabsTflTubeMapRoute,
  MainLabsThreadTreeRoute: MainLabsThreadTreeRoute,
  MainLabsTidRoute: MainLabsTidRoute,
  MainLabsTimestampRoute: MainLabsTimestampRoute,
  MainLabsTypingRoute: MainLabsTypingRoute,
  MainLabsUaRoute: MainLabsUaRoute,
  MainLabsUnicodeRoute: MainLabsUnicodeRoute,
  MainLabsUnitsRoute: MainLabsUnitsRoute,
  MainLabsVerseRevealRoute: MainLabsVerseRevealRoute,
  MainLabsWhoisRoute: MainLabsWhoisRoute,
  MainLabsWordleRoute: MainLabsWordleRoute,
  MainProjectsNameRoute: MainProjectsNameRoute,
  MainWatchingRkeyRoute: MainWatchingRkeyRoute,
  MainBlogIndexRoute: MainBlogIndexRoute,
  MainGamesIndexRoute: MainGamesIndexRoute,
  MainLabsIndexRoute: MainLabsIndexRoute,
  MainProjectsIndexRoute: MainProjectsIndexRoute,
  MainWatchingIndexRoute: MainWatchingIndexRoute,
  MainLabsAtUriSplatRoute: MainLabsAtUriSplatRoute,
  MainLabsCarExplorerSplatRoute: MainLabsCarExplorerSplatRoute,
  MainLabsCssBattlesDateRoute: MainLabsCssBattlesDateRoute,
  MainLabsFeedSplatRoute: MainLabsFeedSplatRoute,
  MainLabsLexiconNsidRoute: MainLabsLexiconNsidRoute,
  MainLabsPlcLogSplatRoute: MainLabsPlcLogSplatRoute,
  MainPokedexRkeyPokeIdRoute: MainPokedexRkeyPokeIdRoute,
  MainLabsAtUriIndexRoute: MainLabsAtUriIndexRoute,
  MainLabsCarExplorerIndexRoute: MainLabsCarExplorerIndexRoute,
  MainLabsCssBattlesIndexRoute: MainLabsCssBattlesIndexRoute,
  MainLabsFeedIndexRoute: MainLabsFeedIndexRoute,
  MainLabsLexiconIndexRoute: MainLabsLexiconIndexRoute,
  MainLabsPlcLogIndexRoute: MainLabsPlcLogIndexRoute,
  MainLabsYearInReviewIndexRoute: MainLabsYearInReviewIndexRoute,
  MainLabsYearInReviewHandleYearRoute: MainLabsYearInReviewHandleYearRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OgSplatRoute: OgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
