/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainUsesRouteImport } from './routes/_main/uses'
import { Route as MainMusicRouteImport } from './routes/_main/music'
import { Route as MainGalleryRouteImport } from './routes/_main/gallery'
import { Route as MainDesignSystemRouteImport } from './routes/_main/design-system'
import { Route as MainWatchingIndexRouteImport } from './routes/_main/watching/index'
import { Route as MainProjectsIndexRouteImport } from './routes/_main/projects/index'
import { Route as MainLabsIndexRouteImport } from './routes/_main/labs/index'
import { Route as MainGamesIndexRouteImport } from './routes/_main/games/index'
import { Route as MainBlogIndexRouteImport } from './routes/_main/blog/index'
import { Route as MainWatchingRkeyRouteImport } from './routes/_main/watching/$rkey'
import { Route as MainProjectsNameRouteImport } from './routes/_main/projects/$name'
import { Route as MainGamesRkeyRouteImport } from './routes/_main/games/$rkey'
import { Route as MainBlogRkeyRouteImport } from './routes/_main/blog/$rkey'
import { Route as MainLabsCssBattlesIndexRouteImport } from './routes/_main/labs/css-battles/index'
import { Route as MainLabsCssBattlesDateRouteImport } from './routes/_main/labs/css-battles/$date'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainUsesRoute = MainUsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => MainRoute,
} as any)
const MainMusicRoute = MainMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => MainRoute,
} as any)
const MainGalleryRoute = MainGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => MainRoute,
} as any)
const MainDesignSystemRoute = MainDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => MainRoute,
} as any)
const MainWatchingIndexRoute = MainWatchingIndexRouteImport.update({
  id: '/watching/',
  path: '/watching/',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsIndexRoute = MainProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsIndexRoute = MainLabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => MainRoute,
} as any)
const MainGamesIndexRoute = MainGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogIndexRoute = MainBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => MainRoute,
} as any)
const MainWatchingRkeyRoute = MainWatchingRkeyRouteImport.update({
  id: '/watching/$rkey',
  path: '/watching/$rkey',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsNameRoute = MainProjectsNameRouteImport.update({
  id: '/projects/$name',
  path: '/projects/$name',
  getParentRoute: () => MainRoute,
} as any)
const MainGamesRkeyRoute = MainGamesRkeyRouteImport.update({
  id: '/games/$rkey',
  path: '/games/$rkey',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogRkeyRoute = MainBlogRkeyRouteImport.update({
  id: '/blog/$rkey',
  path: '/blog/$rkey',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCssBattlesIndexRoute = MainLabsCssBattlesIndexRouteImport.update({
  id: '/labs/css-battles/',
  path: '/labs/css-battles/',
  getParentRoute: () => MainRoute,
} as any)
const MainLabsCssBattlesDateRoute = MainLabsCssBattlesDateRouteImport.update({
  id: '/labs/css-battles/$date',
  path: '/labs/css-battles/$date',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/design-system': typeof MainDesignSystemRoute
  '/gallery': typeof MainGalleryRoute
  '/music': typeof MainMusicRoute
  '/uses': typeof MainUsesRoute
  '/blog/$rkey': typeof MainBlogRkeyRoute
  '/games/$rkey': typeof MainGamesRkeyRoute
  '/projects/$name': typeof MainProjectsNameRoute
  '/watching/$rkey': typeof MainWatchingRkeyRoute
  '/blog/': typeof MainBlogIndexRoute
  '/games/': typeof MainGamesIndexRoute
  '/labs/': typeof MainLabsIndexRoute
  '/projects/': typeof MainProjectsIndexRoute
  '/watching/': typeof MainWatchingIndexRoute
  '/labs/css-battles/$date': typeof MainLabsCssBattlesDateRoute
  '/labs/css-battles/': typeof MainLabsCssBattlesIndexRoute
}
export interface FileRoutesByTo {
  '/design-system': typeof MainDesignSystemRoute
  '/gallery': typeof MainGalleryRoute
  '/music': typeof MainMusicRoute
  '/uses': typeof MainUsesRoute
  '/': typeof MainIndexRoute
  '/blog/$rkey': typeof MainBlogRkeyRoute
  '/games/$rkey': typeof MainGamesRkeyRoute
  '/projects/$name': typeof MainProjectsNameRoute
  '/watching/$rkey': typeof MainWatchingRkeyRoute
  '/blog': typeof MainBlogIndexRoute
  '/games': typeof MainGamesIndexRoute
  '/labs': typeof MainLabsIndexRoute
  '/projects': typeof MainProjectsIndexRoute
  '/watching': typeof MainWatchingIndexRoute
  '/labs/css-battles/$date': typeof MainLabsCssBattlesDateRoute
  '/labs/css-battles': typeof MainLabsCssBattlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/design-system': typeof MainDesignSystemRoute
  '/_main/gallery': typeof MainGalleryRoute
  '/_main/music': typeof MainMusicRoute
  '/_main/uses': typeof MainUsesRoute
  '/_main/': typeof MainIndexRoute
  '/_main/blog/$rkey': typeof MainBlogRkeyRoute
  '/_main/games/$rkey': typeof MainGamesRkeyRoute
  '/_main/projects/$name': typeof MainProjectsNameRoute
  '/_main/watching/$rkey': typeof MainWatchingRkeyRoute
  '/_main/blog/': typeof MainBlogIndexRoute
  '/_main/games/': typeof MainGamesIndexRoute
  '/_main/labs/': typeof MainLabsIndexRoute
  '/_main/projects/': typeof MainProjectsIndexRoute
  '/_main/watching/': typeof MainWatchingIndexRoute
  '/_main/labs/css-battles/$date': typeof MainLabsCssBattlesDateRoute
  '/_main/labs/css-battles/': typeof MainLabsCssBattlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/gallery'
    | '/music'
    | '/uses'
    | '/blog/$rkey'
    | '/games/$rkey'
    | '/projects/$name'
    | '/watching/$rkey'
    | '/blog/'
    | '/games/'
    | '/labs/'
    | '/projects/'
    | '/watching/'
    | '/labs/css-battles/$date'
    | '/labs/css-battles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design-system'
    | '/gallery'
    | '/music'
    | '/uses'
    | '/'
    | '/blog/$rkey'
    | '/games/$rkey'
    | '/projects/$name'
    | '/watching/$rkey'
    | '/blog'
    | '/games'
    | '/labs'
    | '/projects'
    | '/watching'
    | '/labs/css-battles/$date'
    | '/labs/css-battles'
  id:
    | '__root__'
    | '/_main'
    | '/_main/design-system'
    | '/_main/gallery'
    | '/_main/music'
    | '/_main/uses'
    | '/_main/'
    | '/_main/blog/$rkey'
    | '/_main/games/$rkey'
    | '/_main/projects/$name'
    | '/_main/watching/$rkey'
    | '/_main/blog/'
    | '/_main/games/'
    | '/_main/labs/'
    | '/_main/projects/'
    | '/_main/watching/'
    | '/_main/labs/css-battles/$date'
    | '/_main/labs/css-battles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/uses': {
      id: '/_main/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof MainUsesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/music': {
      id: '/_main/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MainMusicRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/gallery': {
      id: '/_main/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof MainGalleryRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/design-system': {
      id: '/_main/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof MainDesignSystemRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/watching/': {
      id: '/_main/watching/'
      path: '/watching'
      fullPath: '/watching/'
      preLoaderRoute: typeof MainWatchingIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/': {
      id: '/_main/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof MainProjectsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/': {
      id: '/_main/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof MainLabsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/games/': {
      id: '/_main/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof MainGamesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/': {
      id: '/_main/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof MainBlogIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/watching/$rkey': {
      id: '/_main/watching/$rkey'
      path: '/watching/$rkey'
      fullPath: '/watching/$rkey'
      preLoaderRoute: typeof MainWatchingRkeyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/$name': {
      id: '/_main/projects/$name'
      path: '/projects/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof MainProjectsNameRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/games/$rkey': {
      id: '/_main/games/$rkey'
      path: '/games/$rkey'
      fullPath: '/games/$rkey'
      preLoaderRoute: typeof MainGamesRkeyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/$rkey': {
      id: '/_main/blog/$rkey'
      path: '/blog/$rkey'
      fullPath: '/blog/$rkey'
      preLoaderRoute: typeof MainBlogRkeyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/css-battles/': {
      id: '/_main/labs/css-battles/'
      path: '/labs/css-battles'
      fullPath: '/labs/css-battles/'
      preLoaderRoute: typeof MainLabsCssBattlesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/labs/css-battles/$date': {
      id: '/_main/labs/css-battles/$date'
      path: '/labs/css-battles/$date'
      fullPath: '/labs/css-battles/$date'
      preLoaderRoute: typeof MainLabsCssBattlesDateRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainDesignSystemRoute: typeof MainDesignSystemRoute
  MainGalleryRoute: typeof MainGalleryRoute
  MainMusicRoute: typeof MainMusicRoute
  MainUsesRoute: typeof MainUsesRoute
  MainIndexRoute: typeof MainIndexRoute
  MainBlogRkeyRoute: typeof MainBlogRkeyRoute
  MainGamesRkeyRoute: typeof MainGamesRkeyRoute
  MainProjectsNameRoute: typeof MainProjectsNameRoute
  MainWatchingRkeyRoute: typeof MainWatchingRkeyRoute
  MainBlogIndexRoute: typeof MainBlogIndexRoute
  MainGamesIndexRoute: typeof MainGamesIndexRoute
  MainLabsIndexRoute: typeof MainLabsIndexRoute
  MainProjectsIndexRoute: typeof MainProjectsIndexRoute
  MainWatchingIndexRoute: typeof MainWatchingIndexRoute
  MainLabsCssBattlesDateRoute: typeof MainLabsCssBattlesDateRoute
  MainLabsCssBattlesIndexRoute: typeof MainLabsCssBattlesIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainDesignSystemRoute: MainDesignSystemRoute,
  MainGalleryRoute: MainGalleryRoute,
  MainMusicRoute: MainMusicRoute,
  MainUsesRoute: MainUsesRoute,
  MainIndexRoute: MainIndexRoute,
  MainBlogRkeyRoute: MainBlogRkeyRoute,
  MainGamesRkeyRoute: MainGamesRkeyRoute,
  MainProjectsNameRoute: MainProjectsNameRoute,
  MainWatchingRkeyRoute: MainWatchingRkeyRoute,
  MainBlogIndexRoute: MainBlogIndexRoute,
  MainGamesIndexRoute: MainGamesIndexRoute,
  MainLabsIndexRoute: MainLabsIndexRoute,
  MainProjectsIndexRoute: MainProjectsIndexRoute,
  MainWatchingIndexRoute: MainWatchingIndexRoute,
  MainLabsCssBattlesDateRoute: MainLabsCssBattlesDateRoute,
  MainLabsCssBattlesIndexRoute: MainLabsCssBattlesIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
